"""
Main module for text boundary mapping.

Pipeline theorized and designed by Chloë Farr.
Base code generated by Chloë Farr, debugged and modified by Cursor Agent.
Detailed instructions about the intention behind original code, purpose, requirement, cases, and logic provided to Cursor Agent for debugging and improvement.
"""

from rapidfuzz import fuzz, process #ignore warning. imported through venv as instructed by requirements.txt.
import xml_obj as XMLOBJ
import re
from collections import Counter
from dataclasses import dataclass, field
from typing import List, Literal, Optional, Dict, Tuple
import proximity_scoring
import text_utils
import paragraph_reordering
import fuzzy_matching
import context_matching
import hyphen_linking
import word_merges
import os
import argparse
import sys

# Split on spaces, commas, exclamation marks, and common OCR error characters (*, ~, etc.)
ADVANCED_SPLIT_RE = re.compile(r"[ ,!*~]+")
HY_PHENS = text_utils.HY_PHENS  # Import from text_utils
WORD_RE = re.compile(r"[a-zA-Z][a-zA-Z0-9-]*")  # Fixed: removed \p{L} which requires regex module

@dataclass
class LLMToken:
    """
    A token (actually a word) from the clean text produced by the LLM.
    """
    word: str = None
    word_normalized: str = None
    matched: bool = False
    article_name: str = None
    page_number: int = None
    w_before: Optional["LLMToken"] = None
    w_after: Optional["LLMToken"] = None

@dataclass
class TokenCandidate:
    """
    A possible interpretation of one or more OCR words.
    """
    clean_form: str                      # e.g. "unconscious", "1966"
    kind: Literal["word", "number", "mixed"]
    # Which OCR words this candidate comes from:
    alto_words: List[XMLOBJ.StringWord]        # length 1 for normal words, 2 for hyphen merges
    # Scores
    fuzzy_score: float                   # lexical similarity (RapidFuzz)
    
    # Fields with default values must come after fields without defaults
    possible_llm_elements_by_fuzzy_match: List[LLMToken] = field(default_factory=list) # List of LLM tokens that are possible matches for the token candidate based on the alto word and llm triplets (fuzzy context matching)
    possible_llm_elements_by_context: List[Tuple[LLMToken, float, float]] = field(default_factory=list) # List of LLM tokens that are possible matches for the token candidate based on the alto word and llm triplets (fuzzy context matching)
    best_llm_element_by_context_fuzzy_score: Optional[LLMToken] = None
    proximity_score: float = 0.0         # geometric plausibility
    best_before_context_fuzzy_score: float = 0.0           # neighbor / LM / vocab context
    best_after_context_fuzzy_score: float = 0.0           # neighbor / LM / vocab context
    numeric_score: float = 0.0           # for digits / numeric plausibility
    total_score: float = 0.0             # weighted combination to actually rank on
    extra: dict = field(default_factory=dict) # Additional metadata

@dataclass
class TokenHypotheses:
    anchor: XMLOBJ.StringWord                # usually the first word in ocr_words
    candidates: List[TokenCandidate] = field(default_factory=list)    # sorted by total_score, best first
    flagged_for_error: bool = False
    # Optional: which candidate has been chosen for canonical text
    chosen_index: Optional[int] = None #idk what this is for
    chosen_LLM_token: Optional[LLMToken] = None
    left_matched: Optional["TokenHypotheses"] = None
    right_matched: Optional["TokenHypotheses"] = None
    best_candidates_by_context: Optional[List[Tuple[TokenCandidate, float, float]]] = None
    # Logical neighbors (what they should be based on clean text sequence)
    # Initialized from ALTO spatial neighbors, but can be modified during paragraph reordering
    anchor_left: Optional[XMLOBJ.StringWord] = None   # Logical left neighbor anchor
    anchor_right: Optional[XMLOBJ.StringWord] = None  # Logical right neighbor anchor

    @property
    def chosen(self) -> Optional[TokenCandidate]:
        if self.chosen_index is None:
            return None
        if 0 <= self.chosen_index < len(self.candidates):
            return self.candidates[self.chosen_index]
        return None

# ============================================================================
# HELPER FUNCTIONS FOR COMMON PATTERNS
# ============================================================================

# ============================================================================
# HELPER FUNCTIONS FOR LINK_HYPHEN_PAIRS
# ============================================================================

# ============================================================================
# HELPER FUNCTIONS FOR SEARCH_FOR_WORD_MERGES
# ============================================================================

# Word merge functions are now imported from word_merges module

# Hyphen-related functions are now imported from hyphen_linking module

# Import context matching functions
calculate_context_scores = context_matching.calculate_context_scores
find_best_candidates_by_context = context_matching.find_best_candidates_by_context
narrow_hypothesis_token_candidates_by_context = context_matching.narrow_hypothesis_token_candidates_by_context
find_best_candidates_for_all_hypothesis_objects = context_matching.find_best_candidates_for_all_hypothesis_objects
_set_bidirectional_link = context_matching._set_bidirectional_link
link_hypothesis_objects_by_context = context_matching.link_hypothesis_objects_by_context
assign_llm_candidates_to_all_token_hypotheses_by_context = context_matching.assign_llm_candidates_to_all_token_hypotheses_by_context
assign_llm_candidates_to_all_token_hypotheses_by_fuzzy_matching = context_matching.assign_llm_candidates_to_all_token_hypotheses_by_fuzzy_matching
_create_alto_to_hypothesis_lookup = context_matching._create_alto_to_hypothesis_lookup
_rerun_context_matching_pipeline = context_matching._rerun_context_matching_pipeline


# Import fuzzy matching utilities
create_llm_word_lookup = fuzzy_matching.create_llm_word_lookup
check_individual_word_match = fuzzy_matching.check_individual_word_match
validate_context_scores = fuzzy_matching.validate_context_scores
should_combine_words = fuzzy_matching.should_combine_words
fuzzy_match_rapid = fuzzy_matching.fuzzy_match_rapid
best_fuzzy_match_rapid = fuzzy_matching.best_fuzzy_match_rapid

# Import hyphen linking functions
split_hyphenated_triplets = hyphen_linking.split_hyphenated_triplets
link_hyphen_pairs = hyphen_linking.link_hyphen_pairs
_check_after_word_match = hyphen_linking._check_after_word_match
_create_combined_hypothesis = hyphen_linking._create_combined_hypothesis
_evaluate_word_combination = hyphen_linking._evaluate_word_combination
_should_prefer_match = hyphen_linking._should_prefer_match
_search_spatially_close_partners = hyphen_linking._search_spatially_close_partners
_search_all_words_for_exact_match = hyphen_linking._search_all_words_for_exact_match
_has_internal_hyphen = hyphen_linking._has_internal_hyphen
_detect_hyphenated_triplet_pattern = hyphen_linking._detect_hyphenated_triplet_pattern
_setup_split_triplets = hyphen_linking._setup_split_triplets
_create_candidate_fuzzy_lookups = hyphen_linking._create_candidate_fuzzy_lookups

# Import word merge functions
search_for_word_merges = word_merges.search_for_word_merges
_create_split_hypotheses = word_merges._create_split_hypotheses

# Context matching functions are now imported from context_matching module

# normalize_for_matching and is_hyphenish moved to text_utils module


def create_LLM_element_list(llm_clean_text: str) -> List[LLMToken]:
    """
    Creates a list of LLM tokens from the clean text.
    set values for word, word_normalized, w_before and w_after for each LLM token.
    """
    tokens = llm_clean_text.split()
    llm_elements: List[LLMToken] = []

    i = 0
    while i < len(tokens):
        word = tokens[i]
        word_normalized = text_utils.normalize_for_matching(word) #removes special characters and whitespace, but not hyphens
        llm_element_before = llm_elements[i-1] if i-1 >= 0 and len(llm_elements) > 0 else None 
        
        llm_element = LLMToken(word=word, word_normalized=word_normalized, w_before=llm_element_before)

        llm_elements.append(llm_element)
        # Set w_after on the previous element now that it's appended
        if i > 0 and len(llm_elements) > 1:
            llm_elements[i-1].w_after = llm_element
        i += 1

    if len(llm_elements) > 0:
        llm_elements[-1].w_after = None # last element has no w_after element

    return llm_elements

def create_hypothesis_list(
    alto_words: List[XMLOBJ.StringWord], 
    clean_vocab: set[str],
    fuzzy_cutoff: float = 80.0
) -> List[TokenHypotheses]:
    """
    Creates a list of TokenHypotheses from the alto words.
    Assigns possible word candidates to each TokenHypotheses object.
    - each fuzzy match above cutoff is a possible token candidate.
    - each token candidate is a possible interpretation of the alto word.
    
    Args:
        alto_words: List of ALTO StringWord objects
        clean_vocab: Set of normalized vocabulary words
        fuzzy_cutoff: Minimum fuzzy match score threshold (default: 80.0)
    
    Returns: List[TokenHypotheses] with candidates set.
    """
    hypothesis_list: List[TokenHypotheses] = []
    for alto_word in alto_words:
        # Initialize logical neighbors from ALTO spatial neighbors
        token_hypothesis_object = TokenHypotheses(
            anchor=alto_word,
            anchor_left=alto_word.before_word,  # Initialize from ALTO spatial neighbor
            anchor_right=alto_word.after_word   # Initialize from ALTO spatial neighbor
        )
        # Decode HTML entities in ALTO word content before fuzzy matching
        decoded_content = text_utils.decode_html_entities(alto_word.content)
        # Normalize the content for matching (removes punctuation, lowercases)
        normalized_content = text_utils.normalize_for_matching(decoded_content)
        
        # First check for exact match in normalized vocab
        if normalized_content in clean_vocab:
            token_hypothesis_object.candidates.append(
                TokenCandidate(clean_form=normalized_content, kind="word", alto_words=[alto_word], fuzzy_score=100.0)
            )
        else:
            # If no exact match, try fuzzy matching
            # Use a lower threshold to catch spelling errors like "Hanol" → "Hanoi" (80% match)
            # These will still go through context matching to ensure correct selection
            token_candidates = fuzzy_match_rapid(normalized_content, clean_vocab, cutoff=fuzzy_cutoff, limit=None)
            for token_candidate in token_candidates:
                token_hypothesis_object.candidates.append(TokenCandidate(clean_form=token_candidate[0], kind="word", alto_words=[alto_word], fuzzy_score=token_candidate[1]))
        hypothesis_list.append(token_hypothesis_object)
    return hypothesis_list

def analyze_ocr_accuracy(hypothesis_list: List[TokenHypotheses], show: bool = True) -> None:
    """
    Analyze OCR accuracy at the very beginning (before any processing).
    Shows breakdown of words by fuzzy match percentage.
    
    Args:
        hypothesis_list: List of TokenHypotheses after initial fuzzy matching
        show: If True, display the analysis. If False, do nothing.
    """
    if not show:
        return
    
    print("\n" + "="*70)
    print("OCR ACCURACY ANALYSIS (At the Very Beginning - Before Any Processing)")
    print("="*70)
    
    total_words = len(hypothesis_list)
    words_100_percent = []  # Exact matches (100% fuzzy score)
    words_80_99_percent = []  # 80-99% fuzzy match
    words_less_than_80 = []  # <80% fuzzy match (no candidates)
    
    for hyp in hypothesis_list:
        decoded = text_utils.decode_html_entities(hyp.anchor.content)
        if not hyp.candidates:
            # No candidates = no fuzzy matches above 80% threshold
            words_less_than_80.append(decoded)
        else:
            # Has at least one candidate (exact or fuzzy match)
            best_fuzzy = max((c.fuzzy_score for c in hyp.candidates), default=0.0)
            if best_fuzzy == 100.0:
                words_100_percent.append(decoded)
            elif best_fuzzy >= 80.0:
                words_80_99_percent.append(decoded)
            else:
                words_less_than_80.append(decoded)
    
    count_100 = len(words_100_percent)
    count_80_99 = len(words_80_99_percent)
    count_less_80 = len(words_less_than_80)
    
    pct_100 = count_100 / total_words * 100 if total_words > 0 else 0
    pct_80_99 = count_80_99 / total_words * 100 if total_words > 0 else 0
    pct_less_80 = count_less_80 / total_words * 100 if total_words > 0 else 0
    
    print(f"\nTotal ALTO words: {total_words}")
    print(f"Words with 100% fuzzy match (exact): {count_100} ({pct_100:.1f}%)")
    print(f"Words with 80-99% fuzzy match: {count_80_99} ({pct_80_99:.1f}%)")
    print(f"Words with <80% fuzzy match: {count_less_80} ({pct_less_80:.1f}%)")
    
    print(f"\n{'='*70}")
    print(f"OCR Accuracy (≥80% match): {(pct_100 + pct_80_99):.1f}% ({(count_100 + count_80_99)}/{total_words} words)")
    print(f"{'='*70}\n")

# Helper functions _create_alto_to_hypothesis_lookup and _rerun_context_matching_pipeline 
# are now imported from context_matching module


def run_candidate_pipeline(hypothesis_list: List[TokenHypotheses], llm_elements: List[LLMToken]) -> List[TokenHypotheses]:
    hypothesis_list = assign_llm_candidates_to_all_token_hypotheses_by_fuzzy_matching(hypothesis_list, llm_elements) # assign possible llm elements to all token hypotheses based onnly on fuzzy matching of each individual word. Doesn't consider context.
    # Process each hypothesis individually since assign_llm_candidates_to_all_token_hypotheses_by_context takes a single TokenHypotheses
    for hypothesis in hypothesis_list:
        assign_llm_candidates_to_all_token_hypotheses_by_context(hypothesis)
    hypothesis_list = narrow_hypothesis_token_candidates_by_context(hypothesis_list) # narrow down the list of token candidates by context based on the before and after alto words.
    hypothesis_list = find_best_candidates_for_all_hypothesis_objects(hypothesis_list, llm_elements) # find the best candidates for all hypothesis objects.
    hypothesis_list = link_hypothesis_objects_by_context(hypothesis_list) # link hypothesis objects by context based on the chosen_LLM_token.w_after and chosen_LLM_token.w_before.
    return hypothesis_list


def run_one_iteration(
    hypothesis_list: List[TokenHypotheses],
    llm_elements: List[LLMToken],
    page: XMLOBJ.Page
) -> List[TokenHypotheses]:
    """
    Run one iteration of the pipeline: hyphen linking, word merges, reference updates, context matching.
    Returns the updated hypothesis list.
    """
    # First, split hyphenated triplets (ALTO "assignment-his" → clean "assignment" "-" "his")
    # This must happen BEFORE hyphen linking to avoid conflicts
    hypothesis_list = split_hyphenated_triplets(hypothesis_list, llm_elements)
    
    # Link hyphen pairs (for word-wrap hyphens and other combinations)
    hypothesis_list = link_hyphen_pairs(hypothesis_list, llm_elements, page)
    
    # Re-run context matching (using helper function to consolidate repeated pattern)
    hypothesis_list = _rerun_context_matching_pipeline(hypothesis_list, llm_elements)
    
    # Search for word merges
    hypothesis_list = search_for_word_merges(hypothesis_list, llm_elements)
    
    # Update before_word/after_word references for split words
    current_anchors = {id(hyp.anchor): hyp.anchor for hyp in hypothesis_list}
    content_to_hypotheses = {}
    for hyp in hypothesis_list:
        content = hyp.anchor.content
        if content not in content_to_hypotheses:
            content_to_hypotheses[content] = []
        content_to_hypotheses[content].append(hyp)
        if hyp.candidates:
            for cand in hyp.candidates:
                for alto_word in cand.alto_words:
                    cand_content = alto_word.content
                    if cand_content not in content_to_hypotheses:
                        content_to_hypotheses[cand_content] = []
                    content_to_hypotheses[cand_content].append(hyp)
    
    for hyp in hypothesis_list:
        anchor = hyp.anchor
        if anchor.before_word is not None and id(anchor.before_word) not in current_anchors:
            original_content = anchor.before_word.content
            if original_content in content_to_hypotheses:
                matching_hyps = content_to_hypotheses[original_content]
                if matching_hyps:
                    anchor.before_word = matching_hyps[-1].anchor
            else:
                from text_utils import decode_html_entities
                decoded = decode_html_entities(original_content)
                split_parts = ADVANCED_SPLIT_RE.split(decoded)
                if len(split_parts) > 1:
                    last_part = split_parts[-1].strip()
                    if last_part:
                        for other_hyp in hypothesis_list:
                            if other_hyp.anchor.content.strip() == last_part:
                                anchor.before_word = other_hyp.anchor
                                break
        
        if anchor.after_word is not None and id(anchor.after_word) not in current_anchors:
            original_content = anchor.after_word.content
            if original_content in content_to_hypotheses:
                matching_hyps = content_to_hypotheses[original_content]
                if matching_hyps:
                    anchor.after_word = matching_hyps[0].anchor
            else:
                from text_utils import decode_html_entities
                decoded = decode_html_entities(original_content)
                split_parts = ADVANCED_SPLIT_RE.split(decoded)
                if len(split_parts) > 1:
                    first_part = split_parts[0].strip()
                    if first_part:
                        for other_hyp in hypothesis_list:
                            if other_hyp.anchor.content.strip() == first_part:
                                anchor.after_word = other_hyp.anchor
                                break
    
    # Re-run context matching with updated references (using helper function)
    hypothesis_list = _rerun_context_matching_pipeline(hypothesis_list, llm_elements)
    
    return hypothesis_list


def run_iterative_pipeline(
    hypothesis_list: List[TokenHypotheses],
    llm_elements: List[LLMToken],
    page: XMLOBJ.Page,
    max_iterations: int = 5
) -> List[TokenHypotheses]:
    """
    Run the pipeline iteratively until stable (no changes) or max_iterations reached.
    Convergence is reached when matched_count, error_count, AND pending_count all remain static.
    """
    prev_matched_count = 0
    prev_error_count = 0
    prev_pending_count = 0
    
    for iteration in range(max_iterations):
        # Count current state
        current_matched = sum(1 for h in hypothesis_list if h.chosen_LLM_token)
        current_errors = sum(1 for h in hypothesis_list if h.flagged_for_error)
        current_pending = sum(1 for h in hypothesis_list if paragraph_reordering.is_pending_word(h))
        
        # Run one iteration
        hypothesis_list = run_one_iteration(hypothesis_list, llm_elements, page)
        
        # Count new state
        new_matched = sum(1 for h in hypothesis_list if h.chosen_LLM_token)
        new_errors = sum(1 for h in hypothesis_list if h.flagged_for_error)
        new_pending = sum(1 for h in hypothesis_list if paragraph_reordering.is_pending_word(h))
        
        # Check if stable (all three metrics unchanged)
        if (new_matched == prev_matched_count and 
            new_errors == prev_error_count and 
            new_pending == prev_pending_count):
            print(f"\nPipeline converged after {iteration + 1} iterations")
            break
        
        prev_matched_count = new_matched
        prev_error_count = new_errors
        prev_pending_count = new_pending
        print(f"Iteration {iteration + 1}: Matched: {new_matched}, Errors: {new_errors}, PENDING: {new_pending}")
    
    return hypothesis_list


if __name__ == "__main__":
    # Parse command-line arguments
    parser = argparse.ArgumentParser(description='Map OCR text to clean LLM text')
    parser.add_argument('--show-ocr-accuracy', action='store_true',
                       help='Display OCR accuracy analysis at the beginning')
    parser.add_argument('--clean-text', type=str, default=None,
                       help='Path to clean text file to use for the pipeline')
    parser.add_argument('--xml-file', type=str, default=None,
                       help='Path to ALTO XML file to use for the pipeline (default: None)')
    parser.add_argument('--output-xml', nargs='?', const='', type=str, default=None,
                       help='Write aligned ALTO XML to this path; if flag given with no path, use outputs/<pagename>/<pagename>_aligned.xml')
    args = parser.parse_args()
    if args.xml_file:
        xml_filename = args.xml_file
    else:
        print("No XML file provided")
        sys.exit(1)
    if args.clean_text:
        with open(f"{args.clean_text}", "r", encoding="utf-8") as f:
            clean_text = f.read()
    else:
        print("No clean text file provided")
        sys.exit(1)

    tokens = clean_text.split()  # raw tokens from clean text

    # List[LLMToken] use this to match LLM tokens to TokenCandidates, and compare alto triplets to LLM triplets
    llm_elements = create_LLM_element_list(clean_text)

    # Create counter (dictionary with word_normalized as key and count as value) of LLM tokens for fuzzy matching and visualization functions
    clean_vocab_counter = Counter(e.word_normalized for e in llm_elements)
    # Convert to set for function calls that expect set[str]
    clean_vocab = set(clean_vocab_counter.keys())

    #from xml, load first page
    page = XMLOBJ.load_first_page(xml_filename)
    page.set_string_page_ids()

    # Extract test page name from path (e.g., "input/1972_10_12_p1/1972_10_12_p1.xml" -> "1972_10_12_p1")
    # Handle both "input/{name}/{name}.xml" and other formats
    xml_path_parts = xml_filename.replace("\\", "/").split("/")
    if len(xml_path_parts) >= 2 and xml_path_parts[0] == "input":
        testpagename = xml_path_parts[1]
    else:
        # Fallback: extract from filename
        testpagename = os.path.splitext(os.path.basename(xml_filename))[0]
    print("\n\n--------- Page Text ---------\n")
    #get list of StringWord objects from the page
    alto_words = page.all_strings()
    page.set_word_triplets(alto_words) # set before_word and after_word for each word in alto_words. Before and After values may change based on the context scoring and matching.

    # Create mapping to track original ALTO word content by anchor ID
    # This allows us to show original words in PDFs even after splits/merges
    original_alto_content_by_id: Dict[int, str] = {}
    for alto_word in alto_words:
        original_alto_content_by_id[id(alto_word)] = text_utils.decode_html_entities(alto_word.content)

    """
    First round of matching:
    """
    hypothesis_list = create_hypothesis_list(alto_words, clean_vocab)
    
    # Analyze OCR accuracy at the VERY BEGINNING (before any processing)
    analyze_ocr_accuracy(hypothesis_list, show=args.show_ocr_accuracy)
    
    # Create visualization of original OCR text before cleaning
    import visualize_matching as viz
    viz.visualize_original_ocr_text(
        hypothesis_list, 
        page, 
        xml_filename, 
        output_dir=os.path.join("outputs", testpagename)
    )
    
    # Now run the candidate pipeline (Round 1)
    hypothesis_list = run_candidate_pipeline(hypothesis_list, llm_elements)
    
    # Capture initial state for before/after comparison
    initial_matched = sum(1 for h in hypothesis_list if h.chosen_LLM_token is not None)
    initial_errors = sum(1 for h in hypothesis_list if h.flagged_for_error)
    initial_pending = sum(1 for h in hypothesis_list if paragraph_reordering.is_pending_word(h))


    """
    Second round of matching:
    Handle hypothesis objects that have no possible token candidates. 
    - First: Try to link hyphen pairs (including non-literal hyphens like "dams" + "aged" = "damaged")
    - Then: Test for word merges/splits
    - Run iteratively until stable
    """
    # Run iterative pipeline until stable
    hypothesis_list = run_iterative_pipeline(hypothesis_list, llm_elements, page, max_iterations=5)

    # Re-run context matching after iterative pipeline (neighbors may have been resolved)
    # First, ensure linking is up to date so context matching can use linked neighbors
    hypothesis_list = link_hypothesis_objects_by_context(hypothesis_list)
    
    # Re-run fuzzy matching to ensure all candidates have fuzzy matches (in case new words were created)
    hypothesis_list = assign_llm_candidates_to_all_token_hypotheses_by_fuzzy_matching(hypothesis_list, llm_elements)
    
    # Re-run context matching for ALL words to pick up newly resolved neighbors
    hypothesis_list = _rerun_context_matching_pipeline(hypothesis_list, llm_elements)

    """
    Cross-boundary matching:
    Link neighbors across layout boundaries for PENDING words.
    Runs after hyphen linking so that hyphenated words are already resolved.
    """
    # Cross-boundary matching: Link neighbors across layout boundaries for PENDING words
    hypothesis_list = paragraph_reordering.reorder_paragraphs(
        hypothesis_list, llm_elements, page
    )
    
    # Re-run context matching after cross-boundary linking (for all words to pick up newly resolved neighbors)
    hypothesis_list = link_hypothesis_objects_by_context(hypothesis_list)
    
    # Re-run fuzzy matching to ensure all candidates have fuzzy matches
    hypothesis_list = assign_llm_candidates_to_all_token_hypotheses_by_fuzzy_matching(hypothesis_list, llm_elements)
    
    # Re-run context matching for ALL words (not just PENDING) to pick up newly resolved neighbors
    hypothesis_list = _rerun_context_matching_pipeline(hypothesis_list, llm_elements)

    """
    Third round of matching:
    Additional processes to handle edge cases:
    - Weak fuzzy matching: Match words with no LLM candidates using bounding box size
    """
    # Weak fuzzy matching (non-intrusive - only fills in unmatched words)
    import weak_fuzzy_matching
    hypothesis_list = weak_fuzzy_matching.match_weak_fuzzy_words(
        hypothesis_list, llm_elements, page
    )
    
    # After weak fuzzy matching resolves conflicts, re-run candidate selection
    # This will match PENDING words that now have available perfect matches
    hypothesis_list = find_best_candidates_for_all_hypothesis_objects(hypothesis_list, llm_elements)
    hypothesis_list = link_hypothesis_objects_by_context(hypothesis_list)
    
    # Final pass: Match PENDING words that have candidates with unmatched LLM tokens
    # This handles cases where words have good candidates but weren't matched due to conflicts
    for hyp in hypothesis_list:
        if hyp.chosen_LLM_token is None and hyp.candidates:
            # Try to find an unmatched LLM token in candidates
            for candidate in hyp.candidates:
                # Check fuzzy matches first
                for llm_token in candidate.possible_llm_elements_by_fuzzy_match:
                    if not llm_token.matched:
                        hyp.chosen_LLM_token = llm_token
                        llm_token.matched = True
                        if candidate in hyp.candidates:
                            hyp.chosen_index = hyp.candidates.index(candidate)
                        hyp.flagged_for_error = False
                        break
                if hyp.chosen_LLM_token:
                    break
                # Check context matches (prefer good context scores)
                if candidate.possible_llm_elements_by_context:
                    # Sort by context score (best first)
                    sorted_context = sorted(
                        candidate.possible_llm_elements_by_context,
                        key=lambda x: (x[1] + x[2]) / 2.0,
                        reverse=True
                    )
                    for llm_token, before_score, after_score in sorted_context:
                        if not llm_token.matched:
                            # Only match if context scores are reasonable (at least one side is good)
                            if before_score >= 70.0 or after_score >= 70.0:
                                hyp.chosen_LLM_token = llm_token
                                llm_token.matched = True
                                if candidate in hyp.candidates:
                                    hyp.chosen_index = hyp.candidates.index(candidate)
                                hyp.flagged_for_error = False
                                break
                if hyp.chosen_LLM_token:
                    break
    
    # Re-link after final matching
    hypothesis_list = link_hypothesis_objects_by_context(hypothesis_list)
    
    # FINAL HARD MATCHING PASS: Match PENDING words based solely on neighbors and position/size
    # This is the very last pass - matches words that have no candidates using hard neighbor/position matching
    pending_hyps = [hyp for hyp in hypothesis_list if hyp.chosen_LLM_token is None and not hyp.flagged_for_error and not hyp.candidates]
    if pending_hyps:
        unmatched_tokens = weak_fuzzy_matching.find_unmatched_llm_tokens(llm_elements, hypothesis_list)
        for pending_hyp in pending_hyps:
            # Get neighbors
            left_neighbor_hyp = None
            right_neighbor_hyp = None
            
            if pending_hyp.anchor.before_word:
                for h in hypothesis_list:
                    if h.anchor == pending_hyp.anchor.before_word:
                        left_neighbor_hyp = h
                        break
                    for candidate in h.candidates:
                        if pending_hyp.anchor.before_word in candidate.alto_words:
                            left_neighbor_hyp = h
                            break
                    if left_neighbor_hyp:
                        break
            
            if pending_hyp.anchor.after_word:
                for h in hypothesis_list:
                    if h.anchor == pending_hyp.anchor.after_word:
                        right_neighbor_hyp = h
                        break
                    for candidate in h.candidates:
                        if pending_hyp.anchor.after_word in candidate.alto_words:
                            right_neighbor_hyp = h
                            break
                    if right_neighbor_hyp:
                        break
            
            # Need at least one neighbor with a match
            if not left_neighbor_hyp and not right_neighbor_hyp:
                continue
            if left_neighbor_hyp and not left_neighbor_hyp.chosen_LLM_token:
                left_neighbor_hyp = None
            if right_neighbor_hyp and not right_neighbor_hyp.chosen_LLM_token:
                right_neighbor_hyp = None
            if not left_neighbor_hyp and not right_neighbor_hyp:
                continue
            
            # HARD MATCHING: Based solely on neighbors, proximity, and word length/size
            # IGNORE fuzzy match of the word itself - rely on context and physical properties
            import text_utils
            
            # Get neighbor texts for matching
            # For hard matching, we compare against the LLM token's actual neighbors (w_before/w_after.word)
            # These are the clean text words, so we should use chosen_LLM_token.word (the matched clean form)
            # However, if the neighbor was hyphenated and merged, we need to ensure we're comparing correctly
            left_neighbor_text = None
            right_neighbor_text = None
            if left_neighbor_hyp:
                if left_neighbor_hyp.chosen_LLM_token:
                    # Use the matched LLM token word (this is the clean form that matches llm_token.w_before.word)
                    # This handles merged/hyphenated words correctly - "resi- + dence" → "residence"
                    left_neighbor_text = text_utils.normalize_for_matching(left_neighbor_hyp.chosen_LLM_token.word)
                else:
                    # Fall back to ALTO content if not matched yet
                    left_alto_decoded = text_utils.decode_html_entities(left_neighbor_hyp.anchor.content)
                    left_neighbor_text = text_utils.normalize_for_matching(left_alto_decoded)
            if right_neighbor_hyp:
                if right_neighbor_hyp.chosen_LLM_token:
                    # Use the matched LLM token word (clean form)
                    right_neighbor_text = text_utils.normalize_for_matching(right_neighbor_hyp.chosen_LLM_token.word)
                else:
                    # Fall back to ALTO content if not matched yet
                    right_alto_decoded = text_utils.decode_html_entities(right_neighbor_hyp.anchor.content)
                    right_neighbor_text = text_utils.normalize_for_matching(right_alto_decoded)
            
            # Get ALTO word properties for size matching
            alto_width = pending_hyp.anchor.width
            alto_height = pending_hyp.anchor.height
            alto_length = len(text_utils.decode_html_entities(pending_hyp.anchor.content))
            
            # Find candidates based ONLY on neighbor strength (ignore word fuzzy match)
            candidates = []
            for llm_token in unmatched_tokens:
                left_score = 0.0
                right_score = 0.0
                
                # Check neighbor matches
                # Compare normalized forms - if neighbor has chosen_LLM_token, use that (clean form)
                # If not, use ALTO content (surface form) but be more lenient since surface forms may differ
                if llm_token.w_before and left_neighbor_text:
                    llm_before_normalized = text_utils.normalize_for_matching(llm_token.w_before.word)
                    # If neighbor has chosen_LLM_token, we're comparing clean forms (should match well)
                    # If neighbor doesn't have chosen_LLM_token, we're comparing ALTO surface form to clean form (may differ)
                    # Use fuzzy matching to handle both cases
                    left_score = fuzz.ratio(left_neighbor_text, llm_before_normalized)
                elif not llm_token.w_before and not left_neighbor_text:
                    left_score = 100.0
                
                if llm_token.w_after and right_neighbor_text:
                    llm_after_normalized = text_utils.normalize_for_matching(llm_token.w_after.word)
                    # Same logic as above
                    right_score = fuzz.ratio(right_neighbor_text, llm_after_normalized)
                elif not llm_token.w_after and not right_neighbor_text:
                    right_score = 100.0
                
                # Require strong neighbor matches - this is the primary criterion
                # For hard matching, be more lenient: require both neighbors ≥85% OR one ≥90% and the other ≥80%
                # This handles cases where one neighbor was hyphenated and merged (surface form vs clean form)
                neighbor_match_ok = False
                if (left_score >= weak_fuzzy_matching.NEIGHBOR_STRENGTH_THRESHOLD and 
                    right_score >= weak_fuzzy_matching.NEIGHBOR_STRENGTH_THRESHOLD):
                    # Both neighbors match very well (≥90%)
                    neighbor_match_ok = True
                elif (left_score >= 85.0 and right_score >= 85.0):
                    # Both neighbors match well (≥85%)
                    neighbor_match_ok = True
                elif ((left_score >= weak_fuzzy_matching.NEIGHBOR_STRENGTH_THRESHOLD and right_score >= 80.0) or
                      (right_score >= weak_fuzzy_matching.NEIGHBOR_STRENGTH_THRESHOLD and left_score >= 80.0)):
                    # One neighbor matches very well (≥90%) and the other matches reasonably (≥80%)
                    neighbor_match_ok = True
                
                if neighbor_match_ok:
                    # Calculate word length similarity (approximate size matching)
                    llm_word_length = len(llm_token.word)
                    length_diff = abs(alto_length - llm_word_length)
                    max_length = max(alto_length, llm_word_length, 1)
                    length_similarity = 100.0 * (1.0 - (length_diff / max_length))
                    
                    # Use a dummy word fuzzy score (not used in scoring, but required by _score_candidate_by_fit)
                    # Set to 50.0 as a neutral value since we're ignoring it
                    dummy_word_fuzzy = 50.0
                    candidates.append((llm_token, left_score, right_score, dummy_word_fuzzy, length_similarity))
            
            if not candidates:
                continue
            
            # Score candidates by fit (proximity/position/size) - this uses bounding box matching
            best_candidate = None
            best_score = 0.0
            for llm_token, left_score, right_score, dummy_word_fuzzy, length_similarity in candidates:
                # Calculate fit score using position/size (ignoring word fuzzy)
                score_result = weak_fuzzy_matching._score_candidate_by_fit(
                    pending_hyp, llm_token, left_score, right_score, dummy_word_fuzzy, hypothesis_list, page
                )
                if score_result:
                    total_score, fit_score = score_result
                    # Combine with length similarity for final score
                    # Weight: 60% fit_score (position/size), 40% length_similarity, with neighbor strength as base
                    combined_score = (fit_score * 0.6) + (length_similarity * 0.4)
                    # Scale by neighbor strength (average of left and right)
                    neighbor_avg = (left_score + right_score) / 2.0
                    final_score = combined_score * (neighbor_avg / 100.0)
                    
                    if final_score > best_score:
                        best_score = final_score
                        best_candidate = (llm_token, left_score, right_score, dummy_word_fuzzy, final_score, fit_score)
            
            # Match if we have a good candidate
            # Lower threshold (65%) since we're relying on neighbors and size, not word similarity
            if best_candidate and best_score >= 65.0:
                llm_token, left_score, right_score, dummy_word_fuzzy, final_score, fit_score = best_candidate
                weak_fuzzy_matching._create_match_for_hypothesis(
                    pending_hyp, llm_token, final_score, left_neighbor_hyp, right_neighbor_hyp
                )
    
    # Re-link after hard matching
    hypothesis_list = link_hypothesis_objects_by_context(hypothesis_list)
    
    # Calculate final state for summary
    final_matched = sum(1 for h in hypothesis_list if h.chosen_LLM_token is not None)
    final_errors = sum(1 for h in hypothesis_list if h.flagged_for_error)
    final_pending = sum(1 for h in hypothesis_list if paragraph_reordering.is_pending_word(h))
    
    # MINIMAL DEBUGGING OUTPUT
    print("\n" + "="*70)
    print("PIPELINE SUMMARY")
    print("="*70)
    
    # Print before/after summary stats
    print(f"\nBEFORE Processing:")
    print(f"  Matched words: {initial_matched}")
    print(f"  Error words: {initial_errors}")
    print(f"  PENDING words: {initial_pending}")
    
    print(f"\nAFTER Processing:")
    print(f"  Matched words: {final_matched} ({final_matched - initial_matched:+d})")
    print(f"  Error words: {final_errors} ({final_errors - initial_errors:+d})")
    print(f"  PENDING words: {final_pending} ({final_pending - initial_pending:+d})")
    
    # List unmatched ALTO words (failed to match)
    unmatched_words = []
    for hyp in hypothesis_list:
        if hyp.chosen_LLM_token is None:
            decoded = text_utils.decode_html_entities(hyp.anchor.content)
            unmatched_words.append(decoded)
    
    if unmatched_words:
        print(f"\nUnmatched ALTO words ({len(unmatched_words)}):")
        # Group by content to avoid duplicates
        unmatched_counts = Counter(unmatched_words)
        for word, count in unmatched_counts.most_common(50):  # Show top 50
            if count > 1:
                print(f"  '{word}' (appears {count} times)")
            else:
                print(f"  '{word}'")
        if len(unmatched_counts) > 50:
            print(f"  ... and {len(unmatched_counts) - 50} more unique words")
    else:
        print("\nAll ALTO words matched successfully!")
    
    print("\n" + "="*70)
    
    # Create visualization of cleaned text positions (after PNG)
    import visualize_matching as viz
    output_dir = os.path.join("outputs", testpagename)
    os.makedirs(output_dir, exist_ok=True)
    viz.visualize_cleaned_text_positions(
        hypothesis_list,
        page,
        testpagename,
        output_dir=output_dir,
        original_alto_content_by_id=original_alto_content_by_id
    )

    if args.output_xml is not None:
        import write_aligned_alto
        out_path = args.output_xml if args.output_xml else os.path.join(output_dir, f"{testpagename}_aligned.xml")
        write_aligned_alto.write_aligned_alto(xml_filename, page, hypothesis_list, out_path)
        print(f"Wrote aligned ALTO XML to {out_path}")

