"""
Main module for text boundary mapping.

Pipeline theorized and designed by Chloë Farr.
Base code generated by Chloë Farr, debugged and modified by Cursor Agent.
Detailed instructions about the intention behind original code, purpose, requirement, cases, and logic provided to Cursor Agent for debugging and improvement.
"""

from xml.etree.ElementTree import Element
from rapidfuzz import fuzz, process
import xml_obj as XMLOBJ
import re
import html
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from typing import List, Literal, Optional, Dict, Tuple
import proximity_scoring


ADVANCED_SPLIT_RE = re.compile(r"[ ,!]+")
HY_PHENS = ("-", "-", "—", "--")  # plain hyphen + common variants
WORD_RE = re.compile(r"[a-zA-Z][a-zA-Z0-9-]*")  # Fixed: removed \p{L} which requires regex module

@dataclass
class LLMToken:
    """
    A token (actually a word) from the clean text produced by the LLM.
    """
    word: str = None
    word_normalized: str = None
    matched: bool = False
    article_name: str = None
    page_number: int = None
    w_before: Optional["LLMToken"] = None
    w_after: Optional["LLMToken"] = None

@dataclass
class TokenCandidate:
    """
    A possible interpretation of one or more OCR words.
    """
    clean_form: str                      # e.g. "unconscious", "1966"
    kind: Literal["word", "number", "mixed"]
    # Which OCR words this candidate comes from:
    alto_words: List[XMLOBJ.StringWord]        # length 1 for normal words, 2 for hyphen merges
    # Scores
    fuzzy_score: float                   # lexical similarity (RapidFuzz)
    
    # Fields with default values must come after fields without defaults
    possible_llm_elements_by_fuzzy_match: List[LLMToken] = field(default_factory=list) # List of LLM tokens that are possible matches for the token candidate based on the alto word and llm triplets (fuzzy context matching)
    possible_llm_elements_by_context: List[Tuple[LLMToken, float, float]] = field(default_factory=list) # List of LLM tokens that are possible matches for the token candidate based on the alto word and llm triplets (fuzzy context matching)
    best_llm_element_by_context_fuzzy_score: Optional[LLMToken] = None
    proximity_score: float = 0.0         # geometric plausibility
    best_before_context_fuzzy_score: float = 0.0           # neighbor / LM / vocab context
    best_after_context_fuzzy_score: float = 0.0           # neighbor / LM / vocab context
    numeric_score: float = 0.0           # for digits / numeric plausibility
    total_score: float = 0.0             # weighted combination to actually rank on
    extra: dict = field(default_factory=dict) # Additional metadata

@dataclass
class TokenHypotheses:
    anchor: XMLOBJ.StringWord                # usually the first word in ocr_words
    candidates: List[TokenCandidate] = field(default_factory=list)    # sorted by total_score, best first
    flagged_for_error: bool = False
    # Optional: which candidate has been chosen for canonical text
    chosen_index: Optional[int] = None #idk what this is for
    chosen_LLM_token: Optional[LLMToken] = None
    left_matched: Optional["TokenHypotheses"] = None
    right_matched: Optional["TokenHypotheses"] = None
    best_candidates_by_context: Optional[List[Tuple[TokenCandidate, float, float]]] = None

    @property
    def chosen(self) -> Optional[TokenCandidate]:
        if self.chosen_index is None:
            return None
        if 0 <= self.chosen_index < len(self.candidates):
            return self.candidates[self.chosen_index]
        return None

@dataclass
class VocabEntry:
    surface: str   # canonical spelling as it should appear ("anti-aircraft")
    norm: str      # normalized form used for matching ("antiaircraft")
    
ALL_HYPOTHESES: Dict[XMLOBJ.StringWord, TokenHypotheses] = {} # Key by anchor StringWord

def decode_html_entities(text: str) -> str:
    """
    Decode HTML entities in text to Unicode characters.
    This is needed because ALTO XML may contain HTML entities (e.g., &amp;, &quot;)
    while the clean text has Unicode characters.
    
    Args:
        text (str): Text that may contain HTML entities
        
    Returns:
        str: Text with HTML entities decoded to Unicode
        
    Example:
        >>> decode_html_entities("&amp;")
        '&'
        >>> decode_html_entities("&quot;hello&quot;")
        '"hello"'
    """
    return html.unescape(text)

def get_fuzzy_match_score(word: str, vocab: set[str], cutoff: float = 90.0) -> Optional[float]:
    """
    Use a dedicated fuzzy library to find best word matches
    cutoff is in [0, 100]
    
    Returns:
    best_match, score or None if no match found
    """
    result = process.extractOne(query=word, choices=vocab, scorer=fuzz.ratio, score_cutoff=cutoff)
    if result is None:
        return None
    return result[1]

def fuzzy_match_rapid(word: str, vocab: set[str], cutoff: float = 90.0, limit: int = None) -> List[Tuple[str, float]]:
    """
    Use a dedicated fuzzy library to find best word matches
    cutoff is in [0, 100]
    
    Returns:
    all strong matches, sorted by score
    """
    return process.extract(query=word, choices=vocab, scorer=fuzz.ratio, score_cutoff=cutoff, limit=None)

def best_fuzzy_match_rapid(word: str, vocab: set[str], cutoff: float = 90.0) -> TokenCandidate | None:
    """
    Use a dedicated fuzzy library to find best word matches
    cutoff is in [0, 100]
    
    Returns:
    best_match, score or None if no match found
    """
    # process.extractOne returns (match, score, index)
    result = process.extractOne(
        query=word,
        choices=vocab,
        scorer=fuzz.ratio,
        score_cutoff=cutoff
    )

    if result is None:
        return None

    match, score, index = result
    # Note: This function creates TokenCandidate with string instead of StringWord - may need redesign
    # For now, using empty list as alto_words requires List[XMLOBJ.StringWord]
    return TokenCandidate(clean_form=match, kind="word", alto_words=[], fuzzy_score=float(score))

def find_best_candidates_by_context(hypothesis_object: TokenHypotheses) -> List[TokenCandidate]:
    """
    Find the best candidate based on the context scores.
    Returns: TokenCandidate with the best context score.
    """
    best_candidates_by_context = []
    perfect_matches = []  # Track perfect matches separately
    
    for candidate in hypothesis_object.candidates:

        if not candidate.possible_llm_elements_by_context:  # Check if list is empty
            continue

        for llm_element, before_score, after_score in candidate.possible_llm_elements_by_context:
            if before_score == 100 and after_score == 100:
                # Perfect match - prioritize these
                perfect_matches.append((candidate, llm_element, before_score, after_score))
            elif len(best_candidates_by_context) == 0 and len(perfect_matches) == 0:
                # First non-perfect match (only if no perfect matches exist)
                best_candidates_by_context.append((candidate, llm_element, before_score, after_score))
            elif len(perfect_matches) == 0:  # Only consider non-perfect matches if no perfect ones exist
                # if the element doesn't have a perfect context score, and there are no perfect scores in the list so far
                if all(best_before < 100 and best_after < 100 
                        for _, _, best_before, best_after in best_candidates_by_context):
                    if (before_score >= max(best_before for _, _, best_before, _ in best_candidates_by_context) or 
                        after_score >= max(best_after for _, _, _, best_after in best_candidates_by_context)):
                        best_candidates_by_context.append((candidate, llm_element, before_score, after_score))

    # Prioritize perfect matches
    if perfect_matches:
        if len(perfect_matches) == 1:
            # Single perfect match - select it immediately
            hypothesis_object.best_candidates_by_context = perfect_matches
            # Also set the chosen token if not already set
            if hypothesis_object.chosen_LLM_token is None:
                hypothesis_object.chosen_LLM_token = perfect_matches[0][1]
                # Set chosen_index
                if perfect_matches[0][0] in hypothesis_object.candidates:
                    hypothesis_object.chosen_index = hypothesis_object.candidates.index(perfect_matches[0][0])
        else:
            # Multiple perfect matches - requires proximity assessment (not yet implemented)
            # Store all perfect matches for later proximity-based selection
            hypothesis_object.best_candidates_by_context = perfect_matches
            # Do not select a match yet - will be handled by proximity assessment
    elif len(best_candidates_by_context) == 1:
        hypothesis_object.best_candidates_by_context = best_candidates_by_context

    return best_candidates_by_context if not perfect_matches else perfect_matches

def narrow_hypothesis_token_candidates_by_context(hypothesis_list: List[TokenHypotheses]) -> List[TokenHypotheses]:
    """
    Narrow down the list of token candidates by context based on the before and after alto words.
    Returns: List[TokenHypotheses] with updated possible_llm_elements_by_context set.
    """
    for token_hypothesis in hypothesis_list:
        likely_candidate = None

        #if all candidates of the hypothesis has no candidates where the possible_llm_elements_by_context is not None, and possible_llm_elements_by_fuzzy_match is not None, remove all candidates and flag it for error
        if all((candidate.possible_llm_elements_by_context is not None and len(candidate.possible_llm_elements_by_context) == 0 and len(candidate.possible_llm_elements_by_fuzzy_match) == 0) for candidate in token_hypothesis.candidates):
            token_hypothesis.flagged_for_error = True
            continue

        # Check for perfect context matches (100/100) and set chosen token immediately
        perfect_matches = []
        for candidate in token_hypothesis.candidates:
            for llm_element, before_score, after_score in candidate.possible_llm_elements_by_context:
                if before_score == 100 and after_score == 100:
                    perfect_matches.append((candidate, llm_element, before_score, after_score))
        
        # If there is only one perfect match, select it immediately
        if len(perfect_matches) == 1:
            candidate, llm_element, _, _ = perfect_matches[0]
            token_hypothesis.chosen_LLM_token = llm_element
            # Set the chosen_index to the candidate's position
            if candidate in token_hypothesis.candidates:
                token_hypothesis.chosen_index = token_hypothesis.candidates.index(candidate)
            continue  # Skip the rest of the processing for this hypothesis
        elif len(perfect_matches) > 1:
            # Multiple perfect matches - requires proximity assessment (not yet implemented)
            # Store all perfect matches for later proximity-based selection
            token_hypothesis.best_candidates_by_context = perfect_matches
            # Do not select a match yet - will be handled by proximity assessment
            continue  # Skip the rest of the processing for this hypothesis
        
        # Check for candidates with 0 context score on one side (when both sides should have matches)
        # This indicates potential hyphenation, merging, or ordering issues
        has_zero_context_on_one_side = False
        anchor = token_hypothesis.anchor
        # Only flag if both before and after words exist (meaning there should be context on both sides)
        if anchor.before_word is not None and anchor.after_word is not None:
            for candidate in token_hypothesis.candidates:
                for llm_element, before_score, after_score in candidate.possible_llm_elements_by_context:
                    # If one side is 0 and the other is > 0, this indicates a problem
                    # (e.g., "day" with before="Wednes-" doesn't match LLM "day"'s before_word)
                    if (before_score == 0.0 and after_score > 0.0) or (before_score > 0.0 and after_score == 0.0):
                        has_zero_context_on_one_side = True
                        break
                if has_zero_context_on_one_side:
                    break
        
        if has_zero_context_on_one_side:
            # Flag for reassessment - might need hyphenation, merging, or incorrect ordering
            token_hypothesis.flagged_for_error = True
            # Don't continue - still process candidates, but flag indicates need for later reassessment

        #find the likely candidate based on the context scores
        # Collect candidates to remove (can't modify list while iterating)
        candidates_to_remove = []
        for candidate in token_hypothesis.candidates:
            for element in candidate.possible_llm_elements_by_context:
                if likely_candidate is None:
                    likely_candidate = element
                elif element[1] > likely_candidate[1] or element[2] > likely_candidate[2]:
                    likely_candidate = element

            # Sort context matches by score for later use (proximity assessment will use these)
            if len(candidate.possible_llm_elements_by_context) > 0:
                candidate.possible_llm_elements_by_context.sort(key=lambda x: x[1]+x[2], reverse=True)
                # Keep the candidate - don't eliminate based on context quality
                # Even imperfect context matches (e.g., 100/50) should be kept for proximity assessment
            elif len(candidate.possible_llm_elements_by_fuzzy_match) == 0:
                # Only mark for deletion if it has neither context matches nor fuzzy matches
                # Keep candidates with fuzzy matches even if context matching failed (e.g., first/last words)
                # Keep candidates with context matches even if imperfect - let proximity assessment decide
                candidates_to_remove.append(candidate)
        
        # Remove candidates marked for deletion
        for candidate in candidates_to_remove:
            token_hypothesis.candidates.remove(candidate)
        
        # Also check best_candidates_by_context if it was already set (for backward compatibility)
        if (token_hypothesis.best_candidates_by_context is not None and 
            len(token_hypothesis.best_candidates_by_context) == 1 and 
            token_hypothesis.best_candidates_by_context[0][2] == 100 and 
            token_hypothesis.best_candidates_by_context[0][3] == 100):
            token_hypothesis.chosen_LLM_token = token_hypothesis.best_candidates_by_context[0][1]

    return hypothesis_list

def find_best_candidates_for_all_hypothesis_objects(hypothesis_list: List[TokenHypotheses], llm_elements: List[LLMToken] = None) -> List[TokenHypotheses]:
    """
    Find the best candidates for all hypothesis objects.
    If llm_elements is provided, uses proximity assessment for multiple perfect matches.
    Returns: List[TokenHypotheses] with updated chosen_llm_token set.
    """

    for hypothesis_object in hypothesis_list:
        find_best_candidates_by_context(hypothesis_object)
        
        # If there are multiple perfect matches and llm_elements, use proximity assessment
        if (hypothesis_object.best_candidates_by_context and 
            len(hypothesis_object.best_candidates_by_context) > 1 and 
            llm_elements is not None):
            best_llm_token = proximity_scoring.assess_proximity_for_multiple_matches(
                hypothesis_object, llm_elements, hypothesis_list
            )
            if best_llm_token:
                hypothesis_object.chosen_LLM_token = best_llm_token
                # Find and set the chosen_index
                for i, candidate in enumerate(hypothesis_object.candidates):
                    for llm_elem, _, _ in candidate.possible_llm_elements_by_context:
                        if llm_elem == best_llm_token:
                            hypothesis_object.chosen_index = i
                            break
                    if hypothesis_object.chosen_index is not None:
                        break
        
        if hypothesis_object.chosen_LLM_token is not None:
            hypothesis_object.chosen_LLM_token.matched = True
    return hypothesis_list

def link_hypothesis_objects_by_context(hypothesis_list: List[TokenHypotheses]) -> List[TokenHypotheses]:
    """
    Link hypothesis objects by context based on the chosen_llm_token.w_after and chosen_llm_token.w_before.
    Returns: List[TokenHypotheses] with updated left_matched and right_matched set.
    """
    for hypothesis_object in hypothesis_list:
        if hypothesis_object.chosen_LLM_token is None:
            continue
        
        # Find the hypothesis to the LEFT (whose chosen_LLM_token matches our w_before)
        # If our chosen_LLM_token.w_before points to another LLM token, find the hypothesis with that token
        if hypothesis_object.chosen_LLM_token.w_before is not None:
            for other_hypothesis_object in hypothesis_list:
                if (other_hypothesis_object.chosen_LLM_token is not None and
                    other_hypothesis_object.chosen_LLM_token == hypothesis_object.chosen_LLM_token.w_before):
                    hypothesis_object.left_matched = other_hypothesis_object
                    other_hypothesis_object.right_matched = hypothesis_object
                    break
        
        # Find the hypothesis to the RIGHT (whose chosen_LLM_token matches our w_after)
        # If our chosen_LLM_token.w_after points to another LLM token, find the hypothesis with that token
        if hypothesis_object.chosen_LLM_token.w_after is not None:
            for other_hypothesis_object in hypothesis_list:
                if (other_hypothesis_object.chosen_LLM_token is not None and
                    other_hypothesis_object.chosen_LLM_token == hypothesis_object.chosen_LLM_token.w_after):
                    hypothesis_object.right_matched = other_hypothesis_object
                    other_hypothesis_object.left_matched = hypothesis_object
                    break

    return hypothesis_list

def assign_llm_candidates_to_all_token_hypotheses_by_context(token_hypothesis: TokenHypotheses, hypothesis_lookup: Optional[Dict[int, TokenHypotheses]] = None) -> TokenHypotheses:
    """
    Assess each token candidate by context based on the before and after alto words.
    If the before or after fuzzy match score is above 90, add the llm element to the possible_llm_elements_by_context list.
        - This allows for the possibility that the triplet on one side is a match, but not the other side.
    If hypothesis_lookup is provided, uses chosen_LLM_token from adjacent hypotheses when available (for split words).
    Returns: TokenCandidate with updated possible_llm_elements_by_context set.
    """
    for token_candidate in token_hypothesis.candidates:
        if len(token_candidate.alto_words) == 0:
            continue
        before_alto_object = token_candidate.alto_words[0].before_word
        after_alto_object = token_candidate.alto_words[0].after_word if len(token_candidate.alto_words) == 1 else token_candidate.alto_words[-1].after_word #handles hyphens and splits

        # Skip only if context matching is not possible (both sides missing)
        # If one side is missing, context matching is still possible on the other side
        if before_alto_object is None and after_alto_object is None:
            continue

        for element in token_candidate.possible_llm_elements_by_fuzzy_match:
            # Check if context matching is possible (at least one side available)
            # If both ALTO and LLM have None for a side, that's a perfect match (both at start/end)
            can_match_before = (before_alto_object is not None) or (element.w_before is None)
            can_match_after = (after_alto_object is not None) or (element.w_after is None)
            
            if not (can_match_before or can_match_after):
                continue
            
            # Get the text to compare for before word
            before_fuzzy_match_score = 0.0
            if before_alto_object is None and element.w_before is None:
                # Both are at the start - perfect match
                before_fuzzy_match_score = 100.0
            elif before_alto_object is not None and element.w_before is not None:
                # Both have before words - compare them
                before_text_to_compare = None
                if hypothesis_lookup and id(before_alto_object) in hypothesis_lookup:
                    before_hyp = hypothesis_lookup[id(before_alto_object)]
                    if before_hyp.chosen_LLM_token:
                        before_text_to_compare = before_hyp.chosen_LLM_token.word
                    else:
                        # Use the best candidate's clean_form if available
                        if before_hyp.candidates:
                            before_text_to_compare = before_hyp.candidates[0].clean_form
                
                if before_text_to_compare is None:
                    # Fall back to ALTO content
                    before_alto_content = decode_html_entities(before_alto_object.content)
                    before_text_to_compare = before_alto_content
                
                # Normalize for comparison
                before_alto_normalized = normalize_for_matching(before_text_to_compare)
                before_llm_normalized = normalize_for_matching(element.w_before.word)
                
                # Compare normalized forms for accurate matching
                before_fuzzy_match_score = fuzz.ratio(before_alto_normalized, before_llm_normalized)
            # If one is None and the other isn't, score remains 0.0 (not a match)
            
            # Get the text to compare for after word
            after_fuzzy_match_score = 0.0
            if after_alto_object is None and element.w_after is None:
                # Both are at the end - perfect match
                after_fuzzy_match_score = 100.0
            elif after_alto_object is not None and element.w_after is not None:
                # Both have after words - compare them
                after_text_to_compare = None
                if hypothesis_lookup and id(after_alto_object) in hypothesis_lookup:
                    after_hyp = hypothesis_lookup[id(after_alto_object)]
                    if after_hyp.chosen_LLM_token:
                        after_text_to_compare = after_hyp.chosen_LLM_token.word
                    else:
                        # Use the best candidate's clean_form if available
                        if after_hyp.candidates:
                            after_text_to_compare = after_hyp.candidates[0].clean_form
                
                if after_text_to_compare is None:
                    # Fall back to ALTO content
                    after_alto_content = decode_html_entities(after_alto_object.content)
                    after_text_to_compare = after_alto_content
                
                # Normalize for comparison
                after_alto_normalized = normalize_for_matching(after_text_to_compare)
                after_llm_normalized = normalize_for_matching(element.w_after.word)
                
                # Compare normalized forms for accurate matching
                after_fuzzy_match_score = fuzz.ratio(after_alto_normalized, after_llm_normalized)
            # If one is None and the other isn't, score remains 0.0 (not a match)

            #if the words match, and both before or after fuzzy match scores are above 90, add the llm element to the possible_llm_elements_by_context list
            if before_fuzzy_match_score > 90 or after_fuzzy_match_score > 90:
                token_candidate.possible_llm_elements_by_context.append((element, float(before_fuzzy_match_score), float(after_fuzzy_match_score)))

    return token_hypothesis


def assign_llm_candidates_to_all_token_hypotheses_by_fuzzy_matching(hypothesis_list: List[TokenHypotheses], llm_elements: List[LLMToken]) -> List[TokenHypotheses]:
    """
    for each hypothesis object (one per alto word), assign possible llm elements to each token candidate based on the clean form and llm word for all possible fuzzy matches
    Returns: List[TokenHypotheses] with possible_llm_elements_by_fuzzy_match set.
    """
    # Create a lookup dictionary for O(1) access instead of O(n) search
    # Map normalized word -> list of LLMTokens with that normalized word
    # Use word_normalized to match against candidate.clean_form (which is also normalized)
    llm_word_lookup: Dict[str, List[LLMToken]] = {}
    for llm_element in llm_elements:
        if llm_element.word_normalized not in llm_word_lookup:
            llm_word_lookup[llm_element.word_normalized] = []
        llm_word_lookup[llm_element.word_normalized].append(llm_element)
    
    # Now iterate through candidates and look up matches efficiently
    for token_hypothesis in hypothesis_list:
        for candidate in token_hypothesis.candidates:
            # O(1) lookup instead of O(n) iteration through all llm_elements
            # candidate.clean_form is normalized, so match against normalized LLM words
            if candidate.clean_form in llm_word_lookup:
                candidate.possible_llm_elements_by_fuzzy_match.extend(llm_word_lookup[candidate.clean_form])

    return hypothesis_list

def normalize_for_matching(word: str) -> str:
    """
    Strips a string of all characters aside from alphanumeric and hyphens. Then strips whitespace.
    Preserves hyphens (including trailing hyphens) to maintain word-wrapping information.
    
    Args:
        word (str): word to clean.

    Returns:
        word (str): word without special characters other than hyphens.

    Example:
    >>> normalize_for_matching("unco-")
    'unco-'

    >>> normalize_for_matching("unconscious.")
    'unconscious'

    >>> normalize_for_matching("unco--nscious")
    'unco--nscious'

    >>> normalize_for_matching("unconscious:")
    'unconscious'
    
    >>> normalize_for_matching("anti-aircraft")
    'antiaircraft'
    """
    s = word.lower()
    # Preserve hyphens (including trailing hyphens that indicate word wrapping)
    # but remove all other non-alphanumeric characters
    # Character class: [^0-9a-z] means "not alphanumeric", then add hyphen variants (regular hyphen (-), en dash (–), em dash (—))
    # In character classes, hyphens must be at start/end or escaped to be literal (e.g. \-)
    s = re.sub(r"[^0-9a-z\-–—]", "", s)  # Preserves all hyphen variants including trailing ones
    return s.strip()  # Only strips whitespace, preserves trailing hyphens


def is_hyphenish(word: XMLOBJ.StringWord) -> bool:
    """
    Determines if a given string contains a hyphen or hyphen-variant.
    
    Args:
        word (str): word to assess.

    Returns:
        bool: True if contains hyphen, False if no hyphen.

    Example:
    >>> is_hyphenish("unco-")
    True

    >>> is_hyphenish("unconscious")
    False

    >>> is_hyphenish("unco--")
    True

    >>> is_hyphenish("unco—")
    True
    """
    # Decode HTML entities before checking for hyphens
    decoded_content = decode_html_entities(word.content)
    return decoded_content.rstrip().endswith(HY_PHENS)


def link_hyphen_pairs(hypothesis_list: List[TokenHypotheses], llm_elements: List[LLMToken], page: XMLOBJ.Page = None) -> List[TokenHypotheses]:
    """
    Links corresponding halves of hyphenated words (or words that should be combined).
    Works with flagged TokenHypotheses objects and uses LLM tokens for matching.
    Handles both literal hyphens and cases where OCR split words incorrectly (e.g., "dams" + "aged" = "damaged").
    
    Args:
        hypothesis_list: List of TokenHypotheses objects (some may be flagged)
        llm_elements: List of LLMToken objects from clean text
        
    Returns:
        List[TokenHypotheses] with hyphen pairs linked and combined
    """
    # Create vocab from LLM elements for matching
    clean_vocab = set(e.word_normalized for e in llm_elements)
    
    # Create lookup: normalized word -> list of LLMTokens
    llm_word_lookup: Dict[str, List[LLMToken]] = {}
    for llm_element in llm_elements:
        if llm_element.word_normalized not in llm_word_lookup:
            llm_word_lookup[llm_element.word_normalized] = []
        llm_word_lookup[llm_element.word_normalized].append(llm_element)
    
    new_hypothesis_list: List[TokenHypotheses] = []
    processed_indices = set()
    
    for i, hyp1 in enumerate(hypothesis_list):
        if i in processed_indices:
            continue
        
        # Process flagged words and words ending with hyphens (potential first half of hyphenated word)
        decoded_w1 = decode_html_entities(hyp1.anchor.content)
        is_literal_hyphen = decoded_w1.rstrip().endswith(HY_PHENS)
        
        if not hyp1.flagged_for_error and not is_literal_hyphen:
            # Not flagged and not a hyphen-ending word, keep as is
            new_hypothesis_list.append(hyp1)
            continue
        
        # Skip if this hypothesis already has candidates with good matches
        # Only process words that truly have no matches at all (need combining with adjacent words)
        # Check if it has candidates with good fuzzy scores or fuzzy matches
        has_good_match = False
        if len(hyp1.candidates) > 0:
            for cand in hyp1.candidates:
                if cand.fuzzy_score >= 85.0 or len(cand.possible_llm_elements_by_fuzzy_match) > 0:
                    has_good_match = True
                    break
        
        if has_good_match:
            # Has good candidates, shouldn't be processed by hyphen linking
            # Keep as is (might have been incorrectly flagged or will match in later stages)
            new_hypothesis_list.append(hyp1)
            continue
        
        # Check if individual word has a good fuzzy match before trying to combine
        normalized_w1 = normalize_for_matching(decoded_w1)
        
        # Check if w1 alone matches something well
        individual_w1_match = None
        if normalized_w1:
            if normalized_w1 in clean_vocab:
                individual_w1_match = (normalized_w1, 100.0)
            else:
                candidate = best_fuzzy_match_rapid(normalized_w1, clean_vocab, cutoff=85.0)
                if candidate:
                    individual_w1_match = (candidate.clean_form, candidate.fuzzy_score)
        
        # base1 is the word without trailing hyphens (for literal hyphen case)
        base1 = decoded_w1.rstrip("-–—") if is_literal_hyphen else decoded_w1
        
        best_match = None
        best_match_score = 0.0
        best_partner_idx = None
        best_llm_token = None
        best_context_score = -1.0  # Track best context score to prefer better matches
        
        # First, check if hyp1 has an after_word set - prioritize that as the partner
        # If after_word exists and matches when combined, use it immediately (highest priority)
        prioritized_indices = []
        after_word_idx = None
        if hyp1.anchor.after_word is not None:
            # Find the index of the after_word in the hypothesis list
            for j in range(i + 1, len(hypothesis_list)):
                if hypothesis_list[j].anchor == hyp1.anchor.after_word:
                    prioritized_indices.append(j)
                    after_word_idx = j
                    break
        
        # Then, collect all other potential partners, sorted by spatial proximity
        other_indices = []
        for j in range(i + 1, len(hypothesis_list)):
            if j not in prioritized_indices:
                other_indices.append(j)
        
        # Detect column boundaries once for this page
        column_boundaries = proximity_scoring.detect_column_boundaries(page)
        
        # Sort other indices by reading order distance (accounts for line/column wrapping)
        def reading_order_distance(idx):
            hyp2 = hypothesis_list[idx]
            return proximity_scoring.calculate_reading_order_distance(hyp1.anchor, hyp2.anchor, page, column_boundaries)
        
        other_indices.sort(key=reading_order_distance)
        
        # If after_word exists, test it FIRST before any other words
        # This ensures the correct match is found when the after_word is the right partner (hard match)
        goto_create_combined = False
        if after_word_idx is not None and after_word_idx not in processed_indices:
            hyp2_after = hypothesis_list[after_word_idx]
            decoded_w2_after = decode_html_entities(hyp2_after.anchor.content)
            normalized_w2_after = normalize_for_matching(decoded_w2_after)
            
            # Try combining with after_word
            if is_literal_hyphen:
                merged_after = base1 + decoded_w2_after
            else:
                merged_after = decoded_w1 + decoded_w2_after
            
            merged_normalized_after = normalize_for_matching(merged_after)
            
            # Check if combined form matches vocab
            if merged_normalized_after in clean_vocab:
                # Found exact match with after_word - use it immediately (hard match)
                matching_llm_tokens_after = llm_word_lookup.get(merged_normalized_after, [])
                if matching_llm_tokens_after:
                    # Use first match - after_word is highest priority
                    best_match = merged_normalized_after
                    best_match_score = 100.0
                    best_partner_idx = after_word_idx
                    best_llm_token = matching_llm_tokens_after[0]
                    best_context_score = 100.0  # After_word match gets highest priority
                    goto_create_combined = True
        
        # Only search other words if a match with after_word was not found
        if not goto_create_combined:
            # Two-pass approach to handle paragraph reordering:
            # Pass 1: Check spatially close words (normal case)
            # Pass 2: Check all remaining words for exact vocabulary matches (handles reordering)
            
            # Pass 1: Combine prioritized first, then spatially sorted others
            search_indices_pass1 = prioritized_indices + other_indices
            
            # Pass 2: All remaining words (for exact vocab matches despite reordering)
            all_other_indices = [j for j in range(i + 1, len(hypothesis_list)) if j not in prioritized_indices]
            
            # Look ahead for potential partners
            # First pass: spatially close words
            for j in search_indices_pass1:
                if j in processed_indices:
                    continue
                    
                hyp2 = hypothesis_list[j]
                
                # Skip words that are too far away in reading order (unless it's the after_word)
                # Use column-aware logic instead of arbitrary distance threshold
                is_after_word = (hyp1.anchor.after_word is not None and hyp2.anchor == hyp1.anchor.after_word)
                if not is_after_word:
                    # Check if words are in adjacent columns (handles cross-column hyphenation)
                    # This is the key case: "sor-" at end of column 1, "ties" at start of column 2
                    are_adjacent_columns = proximity_scoring.are_words_in_adjacent_columns(hyp1.anchor, hyp2.anchor, column_boundaries)
                    
                    if not are_adjacent_columns:
                        # If not in adjacent columns, use reading order distance with column-aware threshold
                        reading_dist = proximity_scoring.calculate_reading_order_distance(hyp1.anchor, hyp2.anchor, page, column_boundaries)
                        
                        # Calculate threshold based on column boundaries (not arbitrary)
                        column_aware_threshold = proximity_scoring.calculate_column_aware_threshold(page, column_boundaries)
                        
                        if reading_dist > column_aware_threshold:
                            continue  # Too far in reading order - skip to pass 2
                
                # Decode and normalize second word
                decoded_w2 = decode_html_entities(hyp2.anchor.content)
                normalized_w2 = normalize_for_matching(decoded_w2)
                
                # Check if w2 alone matches something well
                individual_w2_match = None
                if normalized_w2:
                    if normalized_w2 in clean_vocab:
                        individual_w2_match = (normalized_w2, 100.0)
                    else:
                        candidate = best_fuzzy_match_rapid(normalized_w2, clean_vocab, cutoff=85.0)
                        if candidate:
                            individual_w2_match = (candidate.clean_form, candidate.fuzzy_score)
                
                # Try combining: base1 + w2 (for literal hyphens) or w1 + w2 (for non-hyphen splits)
                if is_literal_hyphen:
                    merged = base1 + decoded_w2
                else:
                    merged = decoded_w1 + decoded_w2
                
                merged_normalized = normalize_for_matching(merged)
                
                if not merged_normalized:
                    continue
                
                # Check for exact match in vocab
                if merged_normalized in clean_vocab:
                    # Found exact match - check context
                    matching_llm_tokens = llm_word_lookup.get(merged_normalized, [])
                    
                    # Use context to find best match
                    # Before word should be hyp1's before_word
                    # After word should be hyp2's after_word
                    before_alto = hyp1.anchor.before_word
                    after_alto = hyp2.anchor.after_word
                    
                    candidate_context_match = None
                    candidate_context_score = 0.0
                    selected_before_score = 0.0
                    selected_after_score = 0.0
                    
                    for llm_token in matching_llm_tokens:
                        if llm_token.w_before is None or llm_token.w_after is None:
                            continue
                        
                        # Check context matches
                        before_score = 0.0
                        after_score = 0.0
                        
                        if before_alto is not None:
                            before_alto_norm = normalize_for_matching(decode_html_entities(before_alto.content))
                            before_llm_norm = normalize_for_matching(llm_token.w_before.word)
                            before_score = fuzz.ratio(before_alto_norm, before_llm_norm)
                        
                        if after_alto is not None:
                            after_alto_norm = normalize_for_matching(decode_html_entities(after_alto.content))
                            after_llm_norm = normalize_for_matching(llm_token.w_after.word)
                            after_score = fuzz.ratio(after_alto_norm, after_llm_norm)
                        
                        # Prefer matches with good context scores
                        context_score = (before_score + after_score) / 2.0
                        if context_score > candidate_context_score:
                            candidate_context_score = context_score
                            candidate_context_match = llm_token
                            selected_before_score = before_score
                            selected_after_score = after_score
                    
                    # Use best context match, or first match if no context available
                    selected_llm = candidate_context_match if candidate_context_match else (matching_llm_tokens[0] if matching_llm_tokens else None)
                    
                    if selected_llm:
                        # Require minimum context scores - at least one side must be > 50% or average > 40%
                        min_context_required = (candidate_context_score > 70.0) or (selected_before_score > 70.0) or (selected_after_score > 70.0)
                        
                        if not min_context_required:
                            # Context scores too low, skip this match
                            continue
                        
                        # Check if individual words have better matches - only combine if combined is significantly better
                        individual_w1_score = individual_w1_match[1] if individual_w1_match else 0.0
                        individual_w2_score = individual_w2_match[1] if individual_w2_match else 0.0
                        best_individual_score = max(individual_w1_score, individual_w2_score)
                        
                        # Only combine if combined match is significantly better (at least 5% better) than individual matches
                        # Or if individual matches are poor (< 85.0)
                        should_combine = False
                        if best_individual_score < 85.0:
                            # Individual words don't match well, combining is reasonable
                            should_combine = True
                        elif 100.0 >= best_individual_score + 5.0:
                            # Combined match is significantly better (at least 5% better)
                            should_combine = True
                        
                        if should_combine:
                            # Only update if this is a better match
                            # Priority: 1) after_word matches (always prefer), 2) exact matches with better context, 3) first exact match
                            should_update = False
                            if best_match is None:
                                should_update = True
                            elif is_after_word:
                                # This is the after_word match - always prefer it over any other match
                                should_update = True
                            elif best_partner_idx is not None and hypothesis_list[best_partner_idx].anchor == hyp1.anchor.after_word:
                                # Current best is already the after_word - don't replace it
                                should_update = False
                            elif best_match_score < 100.0:
                                # Prefer exact matches over fuzzy
                                should_update = True
                            elif best_match_score == 100.0 and candidate_context_score > best_context_score:
                                # Among exact matches, prefer better context (but not over after_word)
                                should_update = True
                            
                            if should_update:
                                best_match = merged_normalized
                                best_match_score = 100.0
                                best_partner_idx = j
                                best_llm_token = selected_llm
                                best_context_score = candidate_context_score
                                
                                # If this is the after_word match, stop searching (it's the best possible match)
                                if is_after_word:
                                    break
                        # Don't break - continue searching for better matches (unless found after_word)
            
            # Pass 2: Check all remaining words for exact vocabulary matches
            # This handles cases where paragraph reordering makes words far apart spatially
            # but they should still be combined (e.g., "sor-" + "ties" = "sorties")
            if best_match_score < 100.0:  # Only if no exact match yet
                for j in all_other_indices:
                    if j in processed_indices or j in search_indices_pass1:
                        continue  # Skip if already processed in pass 1
                    
                    hyp2 = hypothesis_list[j]
                    
                    # Decode and normalize second word
                    decoded_w2 = decode_html_entities(hyp2.anchor.content)
                    normalized_w2 = normalize_for_matching(decoded_w2)
                    
                    # Try combining: base1 + w2 (for literal hyphens) or w1 + w2 (for non-hyphen splits)
                    if is_literal_hyphen:
                        merged = base1 + decoded_w2
                    else:
                        merged = decoded_w1 + decoded_w2
                    
                    merged_normalized = normalize_for_matching(merged)
                    
                    if not merged_normalized:
                        continue
                    
                    # Only check for exact vocabulary matches in pass 2 (not fuzzy)
                    # This prioritizes exact matches even when words are far apart due to reordering
                    if merged_normalized in clean_vocab:
                        # Found exact match - this is a valid combination despite distance
                        matching_llm_tokens = llm_word_lookup.get(merged_normalized, [])
                        if matching_llm_tokens:
                            # Use first match - exact vocab match gets priority
                            # Note: Skip context checking here since spatial distance is unreliable
                            # due to paragraph reordering. The exact vocab match is strong enough.
                            best_match = merged_normalized
                            best_match_score = 100.0
                            best_partner_idx = j
                            best_llm_token = matching_llm_tokens[0]
                            best_context_score = 100.0  # Exact vocab match gets high priority
                            break  # Found exact match, stop searching for better matches
            else:
                # Try fuzzy match (only if no exact match yet)
                if best_match_score < 100.0:
                    candidate = best_fuzzy_match_rapid(merged_normalized, clean_vocab, cutoff=80.0)
                    if candidate and candidate.fuzzy_score > best_match_score:
                        # Check if matching LLM tokens found
                        matching_llm_tokens = llm_word_lookup.get(candidate.clean_form, [])
                        if matching_llm_tokens:
                            # Use context to select best LLM token
                            before_alto = hyp1.anchor.before_word
                            after_alto = hyp2.anchor.after_word
                            
                            candidate_context_match = None
                            candidate_context_score = 0.0
                            selected_before_score = 0.0
                            selected_after_score = 0.0
                            
                            for llm_token in matching_llm_tokens:
                                if llm_token.w_before is None or llm_token.w_after is None:
                                    continue
                                
                                before_score = 0.0
                                after_score = 0.0
                                
                                if before_alto is not None:
                                    before_alto_norm = normalize_for_matching(decode_html_entities(before_alto.content))
                                    before_llm_norm = normalize_for_matching(llm_token.w_before.word)
                                    before_score = fuzz.ratio(before_alto_norm, before_llm_norm)
                                
                                if after_alto is not None:
                                    after_alto_norm = normalize_for_matching(decode_html_entities(after_alto.content))
                                    after_llm_norm = normalize_for_matching(llm_token.w_after.word)
                                    after_score = fuzz.ratio(after_alto_norm, after_llm_norm)
                                
                                context_score = (before_score + after_score) / 2.0
                                if context_score > candidate_context_score:
                                    candidate_context_score = context_score
                                    candidate_context_match = llm_token
                                    selected_before_score = before_score
                                    selected_after_score = after_score
                            
                            selected_llm = candidate_context_match if candidate_context_match else (matching_llm_tokens[0] if matching_llm_tokens else None)
                            
                            if selected_llm:
                                # Require minimum context scores - at least one side must be > 50% or average > 40%
                                min_context_required = (candidate_context_score > 70.0) or (selected_before_score > 70.0) or (selected_after_score > 70.0)
                                
                                if not min_context_required:
                                    # Context scores too low, skip this match
                                    continue
                                
                                # Check if individual words have better matches - only combine if combined is significantly better
                                individual_w1_score = individual_w1_match[1] if individual_w1_match else 0.0
                                individual_w2_score = individual_w2_match[1] if individual_w2_match else 0.0
                                best_individual_score = max(individual_w1_score, individual_w2_score)
                                
                                # Only combine if combined match is significantly better (at least 5% better) than individual matches
                                # Or if individual matches are poor (< 85.0)
                                should_combine = False
                                if best_individual_score < 85.0:
                                    # Individual words don't match well, combining is reasonable
                                    should_combine = True
                                elif candidate.fuzzy_score > best_individual_score + 5.0:
                                    # Combined match is significantly better
                                    should_combine = True
                                
                                if should_combine:
                                    # Only update if better fuzzy score or better context
                                    if (candidate.fuzzy_score > best_match_score or
                                        (candidate.fuzzy_score == best_match_score and candidate_context_score > best_context_score)):
                                        best_match = candidate.clean_form
                                        best_match_score = candidate.fuzzy_score
                                        best_partner_idx = j
                                        best_llm_token = selected_llm
                                        best_context_score = candidate_context_score
        
        # If match found, create combined hypothesis
        if best_match and best_partner_idx is not None:
            hyp2 = hypothesis_list[best_partner_idx]
            
            # Calculate actual context scores
            before_score = 0.0
            after_score = 0.0
            
            if hyp1.anchor.before_word is not None and best_llm_token.w_before is not None:
                before_alto_norm = normalize_for_matching(decode_html_entities(hyp1.anchor.before_word.content))
                before_llm_norm = normalize_for_matching(best_llm_token.w_before.word)
                before_score = fuzz.ratio(before_alto_norm, before_llm_norm)
            
            if hyp2.anchor.after_word is not None and best_llm_token.w_after is not None:
                after_alto_norm = normalize_for_matching(decode_html_entities(hyp2.anchor.after_word.content))
                after_llm_norm = normalize_for_matching(best_llm_token.w_after.word)
                after_score = fuzz.ratio(after_alto_norm, after_llm_norm)
            
            # Create combined TokenHypotheses
            # Use hyp1's anchor as base, but combine both words
            combined_anchor = hyp1.anchor
            combined_hypothesis = TokenHypotheses(anchor=combined_anchor)
            
            # Create candidate with both ALTO words
            combined_candidate = TokenCandidate(
                clean_form=best_match,
                kind="word",
                alto_words=[hyp1.anchor, hyp2.anchor],
                fuzzy_score=best_match_score
            )
            combined_candidate.possible_llm_elements_by_fuzzy_match = [best_llm_token]
            combined_candidate.possible_llm_elements_by_context = [(best_llm_token, before_score, after_score)]
            combined_hypothesis.candidates.append(combined_candidate)
            combined_hypothesis.chosen_LLM_token = best_llm_token
            combined_hypothesis.chosen_index = 0
            combined_hypothesis.flagged_for_error = False
            
            # Set context: before word from hyp1, after word from hyp2
            combined_hypothesis.anchor.before_word = hyp1.anchor.before_word
            combined_hypothesis.anchor.after_word = hyp2.anchor.after_word
            
            new_hypothesis_list.append(combined_hypothesis)
            processed_indices.add(i)
            processed_indices.add(best_partner_idx)
        else:
            # No match found, keep original
            new_hypothesis_list.append(hyp1)
    
    return new_hypothesis_list

def search_for_word_merges(hypothesis_list: List[TokenHypotheses], llm_elements: List[LLMToken]) -> List[TokenHypotheses]:
    """
    Handle word merges in the hypothesis list.
    Returns: List[TokenHypotheses] with updated left_matched and right_matched set.
    """
    # Build new list instead of modifying in place (more efficient)
    new_hypothesis_list: List[TokenHypotheses] = []
    
    for hypothesis_object in hypothesis_list:
        if not hypothesis_object.flagged_for_error:
            # Not flagged, keep as is
            new_hypothesis_list.append(hypothesis_object)
            continue
            
        # test fuzzy matching on words that might be 2 actual words merged into one. Split by special characters.
        # Decode HTML entities before splitting
        decoded_anchor_content = decode_html_entities(hypothesis_object.anchor.content)
        split_words = ADVANCED_SPLIT_RE.split(decoded_anchor_content)
        
        if len(split_words) <= 1:
            # Can't split, keep original
            new_hypothesis_list.append(hypothesis_object)
            continue
            
        # Create list of hypothesis objects for split words
        anchor = hypothesis_object.anchor
        split_hypotheses_objects: List[TokenHypotheses] = []
        
        # Get clean vocab for fuzzy matching (need to pass it or get it from llm_elements)
        # Create vocab from llm_elements
        clean_vocab = set(e.word_normalized for e in llm_elements)
        
        for word in split_words:
            # Normalize the split word for matching
            normalized_word = normalize_for_matching(word)
            
            # Create hypothesis object for this split word
            split_anchor = XMLOBJ.StringWord(
                id=anchor.id, 
                width=anchor.width, 
                height=anchor.height, 
                hpos=anchor.hpos, 
                vpos=anchor.vpos, 
                content=word, 
                wc=anchor.wc
            )
            split_hypothesis = TokenHypotheses(anchor=split_anchor)
            
            # Create candidates for this split word (similar to create_hypothesis_list)
            # First check for exact match in normalized vocab
            if normalized_word in clean_vocab:
                split_hypothesis.candidates.append(
                    TokenCandidate(clean_form=normalized_word, kind="word", alto_words=[split_anchor], fuzzy_score=100.0)
                )
            else:
                # If no exact match, try fuzzy matching
                token_candidates = fuzzy_match_rapid(normalized_word, clean_vocab, cutoff=90.0, limit=None)
                for token_candidate in token_candidates:
                    split_hypothesis.candidates.append(
                        TokenCandidate(clean_form=token_candidate[0], kind="word", alto_words=[split_anchor], fuzzy_score=token_candidate[1])
                    )
            
            split_hypotheses_objects.append(split_hypothesis)
        
        # Assign possible llm elements based on fuzzy matching
        split_hypotheses_objects = assign_llm_candidates_to_all_token_hypotheses_by_fuzzy_matching(
            split_hypotheses_objects, llm_elements
        )
        
        # Run context matching pipeline on split hypotheses to get full matches
        # Set word triplets for split hypotheses:
        # - First split: before_word = original's before_word, after_word = second split (if exists)
        # - Middle splits: before_word = previous split, after_word = next split
        # - Last split: before_word = previous split (if exists), after_word = original's after_word
        for i, split_hyp in enumerate(split_hypotheses_objects):
            if i == 0:
                # First split
                split_hyp.anchor.before_word = anchor.before_word
                if len(split_hypotheses_objects) > 1:
                    split_hyp.anchor.after_word = split_hypotheses_objects[1].anchor
                else:
                    split_hyp.anchor.after_word = anchor.after_word
            elif i == len(split_hypotheses_objects) - 1:
                # Last split
                split_hyp.anchor.before_word = split_hypotheses_objects[i-1].anchor
                split_hyp.anchor.after_word = anchor.after_word
            else:
                # Middle split
                split_hyp.anchor.before_word = split_hypotheses_objects[i-1].anchor
                split_hyp.anchor.after_word = split_hypotheses_objects[i+1].anchor
        
        # First pass: Process each split hypothesis for context matching (using raw ALTO content)
        for split_hyp in split_hypotheses_objects:
            assign_llm_candidates_to_all_token_hypotheses_by_context(split_hyp)
        
        # Narrow down and find best candidates
        split_hypotheses_objects = narrow_hypothesis_token_candidates_by_context(split_hypotheses_objects)
        split_hypotheses_objects = find_best_candidates_for_all_hypothesis_objects(split_hypotheses_objects, llm_elements)
        
        # Second pass: Re-run context matching with lookup to use chosen_LLM_token from adjacent splits
        # This gives better context scores when adjacent splits have been resolved
        # Use object IDs as keys since StringWord objects aren't hashable
        split_hypothesis_lookup: Dict[int, TokenHypotheses] = {
            id(split_hyp.anchor): split_hyp for split_hyp in split_hypotheses_objects
        }
        
        # Re-run context matching with lookup to get improved scores
        for split_hyp in split_hypotheses_objects:
            # Clear existing context matches and re-compute with better context
            for candidate in split_hyp.candidates:
                candidate.possible_llm_elements_by_context.clear()
            assign_llm_candidates_to_all_token_hypotheses_by_context(split_hyp, split_hypothesis_lookup)
        
        # Re-narrow and re-select with improved context scores
        split_hypotheses_objects = narrow_hypothesis_token_candidates_by_context(split_hypotheses_objects)
        split_hypotheses_objects = find_best_candidates_for_all_hypothesis_objects(split_hypotheses_objects, llm_elements)
        
        # Optimize: Create lookup dictionaries for O(1) membership testing
        # Use id() as key since LLMToken might not be hashable
        # Build lookup maps: map LLMToken id -> index in list for fast lookups
        candidate_fuzzy_lookups: List[Dict[int, LLMToken]] = []
        for split_hyp in split_hypotheses_objects:
            lookup = {}
            if len(split_hyp.candidates) > 0:
                # Build a dict mapping id(token) -> token for fast lookups
                for token in split_hyp.candidates[0].possible_llm_elements_by_fuzzy_match:
                    lookup[id(token)] = token
            candidate_fuzzy_lookups.append(lookup)
        
        # Now do the linking with optimized lookups
        for i, split_hypothesis_object in enumerate(split_hypotheses_objects):
            if len(split_hypothesis_object.candidates) == 0:
                continue
                
            candidate = split_hypothesis_object.candidates[0]
            next_lookup = candidate_fuzzy_lookups[i + 1] if i + 1 < len(candidate_fuzzy_lookups) else {}
            prev_lookup = candidate_fuzzy_lookups[i - 1] if i - 1 >= 0 else {}
            current_lookup = candidate_fuzzy_lookups[i]
            
            # Create a list to track what we've already processed to avoid duplicates
            processed_next = set()
            processed_prev = set()
            
            for llm_element in candidate.possible_llm_elements_by_fuzzy_match:
                # Check if next element's w_after matches any element in next candidate's list
                if (i + 1 < len(split_hypotheses_objects) and 
                    llm_element.w_after is not None and
                    id(llm_element.w_after) in next_lookup):
                    # Add cross-references (avoid duplicates)
                    elem_id = id(llm_element)
                    if elem_id not in processed_next:
                        if elem_id not in current_lookup:
                            candidate.possible_llm_elements_by_fuzzy_match.append(llm_element)
                            current_lookup[elem_id] = llm_element
                        if len(split_hypotheses_objects[i+1].candidates) > 0:
                            after_id = id(llm_element.w_after)
                            if after_id not in candidate_fuzzy_lookups[i + 1]:
                                split_hypotheses_objects[i+1].candidates[0].possible_llm_elements_by_fuzzy_match.append(llm_element.w_after)
                                candidate_fuzzy_lookups[i + 1][after_id] = llm_element.w_after
                        processed_next.add(elem_id)

                # Check if previous element's w_before matches any element in prev candidate's list
                if (i - 1 >= 0 and 
                    llm_element.w_before is not None and
                    id(llm_element.w_before) in prev_lookup):
                    # Add cross-references (avoid duplicates)
                    elem_id = id(llm_element)
                    if elem_id not in processed_prev:
                        if elem_id not in current_lookup:
                            candidate.possible_llm_elements_by_fuzzy_match.append(llm_element)
                            current_lookup[elem_id] = llm_element
                        if len(split_hypotheses_objects[i-1].candidates) > 0:
                            before_id = id(llm_element.w_before)
                            if before_id not in candidate_fuzzy_lookups[i - 1]:
                                split_hypotheses_objects[i-1].candidates[0].possible_llm_elements_by_fuzzy_match.append(llm_element.w_before)
                                candidate_fuzzy_lookups[i - 1][before_id] = llm_element.w_before
                        processed_prev.add(elem_id)
                        break  # Only process first match
        
        # Add all split hypotheses to the new list
        new_hypothesis_list.extend(split_hypotheses_objects)
    
    return new_hypothesis_list

def create_LLM_element_list(llm_clean_text: str) -> List[LLMToken]:
    """
    Creates a list of LLM tokens from the clean text.
    set values for word, word_normalized, w_before and w_after for each LLM token.
    TODO: handle getting page number and article name from the clean text.
    """
    tokens = llm_clean_text.split()
    llm_elements: List[LLMToken] = []

    i = 0
    while i < len(tokens):
        word = tokens[i]
        word_normalized = normalize_for_matching(word) #removes special characters and whitespace, but not hyphens
        llm_element_before = llm_elements[i-1] if i-1 >= 0 and len(llm_elements) > 0 else None 
        
        llm_element = LLMToken(word=word, word_normalized=word_normalized, w_before=llm_element_before)

        llm_elements.append(llm_element)
        # Set w_after on the previous element now that it's appended
        if i > 0 and len(llm_elements) > 1:
            llm_elements[i-1].w_after = llm_element
        i += 1

    if len(llm_elements) > 0:
        llm_elements[-1].w_after = None # last element has no w_after element

    return llm_elements

def create_hypothesis_list(alto_words: List[XMLOBJ.StringWord], clean_vocab: set[str]) -> List[TokenHypotheses]:
    """
    Creates a list of TokenHypotheses from the alto words.
    Assigns possible word candidates to each TokenHypotheses object.
    - each fuzzy match above 90 is a possible token candidate.
    - each token candidate is a possible interpretation of the alto word.
    Returns: List[TokenHypotheses] with candidates set.
    """
    hypothesis_list: List[TokenHypotheses] = []
    for alto_word in alto_words:
        token_hypothesis_object = TokenHypotheses(anchor=alto_word)
        # Decode HTML entities in ALTO word content before fuzzy matching
        decoded_content = decode_html_entities(alto_word.content)
        # Normalize the content for matching (removes punctuation, lowercases)
        normalized_content = normalize_for_matching(decoded_content)
        
        # First check for exact match in normalized vocab
        if normalized_content in clean_vocab:
            token_hypothesis_object.candidates.append(
                TokenCandidate(clean_form=normalized_content, kind="word", alto_words=[alto_word], fuzzy_score=100.0)
            )
        else:
            # If no exact match, try fuzzy matching
            # Use a lower threshold (80.0) to catch spelling errors like "Hanol" → "Hanoi" (80% match)
            # These will still go through context matching to ensure correct selection
            token_candidates = fuzzy_match_rapid(normalized_content, clean_vocab, cutoff=80.0, limit=None)
            for token_candidate in token_candidates:
                token_hypothesis_object.candidates.append(TokenCandidate(clean_form=token_candidate[0], kind="word", alto_words=[alto_word], fuzzy_score=token_candidate[1]))
        hypothesis_list.append(token_hypothesis_object)
    return hypothesis_list

def run_candidate_pipeline(hypothesis_list: List[TokenHypotheses], llm_elements: List[LLMToken]) -> List[TokenHypotheses]:
    hypothesis_list = assign_llm_candidates_to_all_token_hypotheses_by_fuzzy_matching(hypothesis_list, llm_elements) # assign possible llm elements to all token hypotheses based onnly on fuzzy matching of each individual word. Doesn't consider context.
    # Process each hypothesis individually since assign_llm_candidates_to_all_token_hypotheses_by_context takes a single TokenHypotheses
    for hypothesis in hypothesis_list:
        assign_llm_candidates_to_all_token_hypotheses_by_context(hypothesis)
    hypothesis_list = narrow_hypothesis_token_candidates_by_context(hypothesis_list) # narrow down the list of token candidates by context based on the before and after alto words.
    hypothesis_list = find_best_candidates_for_all_hypothesis_objects(hypothesis_list, llm_elements) # find the best candidates for all hypothesis objects.
    hypothesis_list = link_hypothesis_objects_by_context(hypothesis_list) # link hypothesis objects by context based on the chosen_LLM_token.w_after and chosen_LLM_token.w_before.
    return hypothesis_list


if __name__ == "__main__":
    clean_text = """
    Witness: Hanoi Heart Raid ’No Error’
    
    HANOI (AP) I witnessed the attack which destroyed the French diplomatic residence, seriously injuring the delegation head, Pierre Susini, and burying four of his Vietnamese staff in debris.

    We were filming one mile away when at least three jets swooped repeatedly over the heart of the capital Wednesday. It was lunch hour. I counted at least a dozen sorties by jets and watched as one, defying heavy anti-aircraft fire, dived very low, dropping two bombs.

    There was no possibility of pilot error. They were attacking very low over the centre of the capital. The area hit is the diplomatic quarter and there are no Vietnamese ministries or factories anywhere near.

    I witnessed and filmed dead taken from rubble of the French residence, which was shorn in half. French Consul Christian Calvy told me the attack came without warning. He called it too horrible for words. He said he could not even imagine French and world reaction. There were at least three bombings. There are five unknown dead in the central area, and probably seven.

    I saw the French delegation head at St. Paul's Hospital in Hanoi. He had extreme facial burns and was still unconscious. A doctor said it was difficult to say if the diplomat would survive, but the doctor believed he could.

    One French diplomat theorized that the bombs were a forced drop from a damaged jet, but this diplomat added he was inside the residence at the time of the attack and did not see the plane. I did, and the low-hitting jet was not damaged.

    Several planes made several sorties. I saw at least three jets. The Canadian military attache here, Maj. Dupuis, says he saw five or six over the city centre.

    Susini had been greeting the Albanian ambassador outside the residence when the bombs dropped. The Albanian escaped with lesser injuries.

    A French diplomat said: "This happens in Vietnam every day and the world pays no attention."

    A British attache said, "The United States has gone too far."


    @ Michael Maclear is a Canadian correspondent based in London for Canada's CTV television network. He now is in Hanoi on assignment—his third trip to North Vietnam. He filed the following report Wednesday to CTV and The Associated Press.
    """

    tokens = clean_text.split()  # raw tokens from clean text

    # List[LLMToken] use this to match LLM tokens to TokenCandidates, and compare alto triplets to LLM triplets
    llm_elements = create_LLM_element_list(clean_text)

    # Create counter (dictionary with word_normalized as key and count as value) of LLM tokens for fuzzy matching and visualization functions
    clean_vocab_counter = Counter(e.word_normalized for e in llm_elements)
    # Convert to set for function calls that expect set[str]
    clean_vocab = set(clean_vocab_counter.keys())

    #From XML file, load the first page - 
    page = XMLOBJ.load_first_page("page-1alto-Maclear.xml")
    print("\n\n--------- Page Text ---------\n")
    #get list of StringWord objects from the page
    alto_words = page.all_strings()
    page.set_word_triplets(alto_words) # set before_word and after_word for each word in alto_words. Before and After values may change based on the context scoring and matching.

    """
    First round of matching:
    """
    hypothesis_list = create_hypothesis_list(alto_words, clean_vocab)
    hypothesis_list = run_candidate_pipeline(hypothesis_list, llm_elements)


    """
    Second round of matching:
    Handle hypothesis objects that have no possible token candidates. 
    - First: Try to link hyphen pairs (including non-literal hyphens like "dams" + "aged" = "damaged")
    - Then: Test for word merges/splits
    """
    # Capture state before hyphen/merge processing for visualization
    hypothesis_list_before_hyphens = hypothesis_list.copy()
    
    # Link hyphen pairs (runs before merge handling)
    hypothesis_list = link_hyphen_pairs(hypothesis_list, llm_elements, page)

    # Create lookup for all ALTO words -> hypotheses (including combined hypotheses)
    # This allows context matching to find resolved values from combined hypotheses
    alto_to_hypothesis_lookup: Dict[int, TokenHypotheses] = {}
    for hyp in hypothesis_list:
        # Map anchor to hypothesis
        alto_to_hypothesis_lookup[id(hyp.anchor)] = hyp
        # Also map all ALTO words in candidates (for combined hypotheses)
        for candidate in hyp.candidates:
            for alto_word in candidate.alto_words:
                alto_to_hypothesis_lookup[id(alto_word)] = hyp
    
    # Re-run context matching with lookup to use resolved values from combined hypotheses
    for hypothesis in hypothesis_list:
        # Clear existing context matches and re-compute with resolved neighbors
        for candidate in hypothesis.candidates:
            candidate.possible_llm_elements_by_context.clear()
        assign_llm_candidates_to_all_token_hypotheses_by_context(hypothesis, alto_to_hypothesis_lookup)
    
    # Re-narrow and re-select with improved context scores
    hypothesis_list = narrow_hypothesis_token_candidates_by_context(hypothesis_list)
    hypothesis_list = find_best_candidates_for_all_hypothesis_objects(hypothesis_list, llm_elements)

    # Re-run linking for hyphen-linked hypotheses to ensure they connect properly
    hypothesis_list = link_hypothesis_objects_by_context(hypothesis_list)

    # Capture state after hyphens, before merges
    hypothesis_list_before_merges = hypothesis_list.copy()

    # Search for word merges in the hypothesis list
    hypothesis_list = search_for_word_merges(hypothesis_list, llm_elements)

    # Re-run linking for split hypotheses to ensure they connect properly with the rest
    hypothesis_list = link_hypothesis_objects_by_context(hypothesis_list)



    # VISUALIZATION
    print("\n" + "="*70)
    print("VISUALIZATION MODE")
    print("="*70)
    
    import visualize_matching as viz
    
    # Show summary dashboard
    viz.create_summary_dashboard(page, clean_vocab, clean_text)
    
    # # Show matching table for first 30 words
    # viz.print_matching_table(page, clean_vocab, max_words=30)
    
    # # Show full pipeline visualization (ALTO → fuzzy → LLM candidates → context → final)
    # # Show initial state before hyphen/merge handling
    # viz.visualize_full_pipeline(hypothesis_list_before_hyphens, max_hypotheses=15)
    
    # # Show hyphen linking process visualization
    # viz.visualize_hyphen_linking_process(hypothesis_list_before_hyphens, hypothesis_list_before_merges)
    
    # # Show word merge splitting process visualization
    # viz.visualize_word_merges_process(hypothesis_list_before_merges, hypothesis_list)
    
    # # Show final state (optional - can be commented out if too verbose)
    # viz.visualize_full_pipeline(hypothesis_list, max_hypotheses=15)
    
    # Show hypothesis sequence mapping (ordered list showing ALTO → LLM mapping)
    viz.visualize_hypothesis_sequence(hypothesis_list, max_hypotheses=100)
    
