"""
Proximity scoring functions for text boundary mapping.

This module handles proximity-based selection when multiple perfect context matches exist.
It uses sequence consistency and geometric position to determine the best match.

Generated by Cursor Agent with detailed instructions about the purpose of the module, cases needing to be handled, and context for the logic.
"""

from typing import List, Optional, Dict, Tuple, TYPE_CHECKING
from collections import defaultdict

# Import types at runtime - using lazy import to avoid circular dependency
if TYPE_CHECKING:
    from map_up_text import LLMToken, TokenHypotheses
    import xml_obj as XMLOBJ
else:
    # At runtime, we'll import inside functions to avoid circular imports
    LLMToken = None
    TokenHypotheses = None
    XMLOBJ = None


def detect_column_boundaries(page) -> Dict[str, List[int]]:
    """
    Analyze the page structure to detect column boundaries dynamically.
    
    Returns a dict with:
    - 'left_edges': List of common left edge positions (column starts)
    - 'right_edges': List of common right edge positions (column ends)
    - 'typical_left': Typical left edge position (most common)
    - 'typical_right': Typical right edge position (most common)
    """
    if page is None:
        return {
            'left_edges': [0, 600],
            'right_edges': [2000, 4000],
            'typical_left': 500,
            'typical_right': 2000
        }
    
    # Collect all TextBlock and TextLine left/right positions
    left_positions = []
    right_positions = []
    
    for block in page.content_elements:
        # TextBlock boundaries
        left_positions.append(block.hpos)
        right_positions.append(block.hpos + block.width)
        
        for line in block.content_elements:
            # TextLine boundaries
            left_positions.append(line.hpos)
            right_positions.append(line.hpos + line.width)
            
            # Also check first and last words in each line
            if line.content_elements:
                first_word = line.content_elements[0]
                last_word = line.content_elements[-1]
                left_positions.append(first_word.hpos)
                right_positions.append(last_word.hpos + last_word.width)
    
    if not left_positions or not right_positions:
        # Fallback to page-based estimates
        return {
            'left_edges': [0, page.width // 2] if page else [0, 600],
            'right_edges': [page.width // 2, page.width] if page else [2000, 4000],
            'typical_left': 500,
            'typical_right': page.width - 500 if page else 2000
        }
    
    # Find common left edge positions (cluster similar positions)
    # Group positions within 100 pixels of each other
    left_positions.sort()
    left_clusters = []
    current_cluster = [left_positions[0]]
    
    for pos in left_positions[1:]:
        if pos - current_cluster[-1] < 100:  # Within 100 pixels
            current_cluster.append(pos)
        else:
            left_clusters.append(current_cluster)
            current_cluster = [pos]
    left_clusters.append(current_cluster)
    
    # Get median of each cluster as a representative left edge
    left_edges = [sorted(cluster)[len(cluster) // 2] for cluster in left_clusters if len(cluster) > 0]
    
    # Find common right edge positions
    right_positions.sort()
    right_clusters = []
    current_cluster = [right_positions[0]]
    
    for pos in right_positions[1:]:
        if pos - current_cluster[-1] < 100:  # Within 100 pixels
            current_cluster.append(pos)
        else:
            right_clusters.append(current_cluster)
            current_cluster = [pos]
    right_clusters.append(current_cluster)
    
    right_edges = [sorted(cluster)[len(cluster) // 2] for cluster in right_clusters if len(cluster) > 0]
    
    # Find most common (typical) positions
    from collections import Counter
    left_counter = Counter(left_positions)
    right_counter = Counter(right_positions)
    
    typical_left = left_counter.most_common(1)[0][0] if left_counter else 500
    typical_right = right_counter.most_common(1)[0][0] if right_counter else (page.width - 500 if page else 2000)
    
    return {
        'left_edges': sorted(set(left_edges)),
        'right_edges': sorted(set(right_edges)),
        'typical_left': typical_left,
        'typical_right': typical_right
    }


def are_words_in_adjacent_columns(word1, word2, column_boundaries: Dict[str, List[int]]) -> bool:
    """
    Check if two words are in adjacent columns.
    
    Returns True if:
    - word1 is at the right edge of one column AND
    - word2 is at the left edge of the next column
    
    This handles cross-column hyphenation like "sor-" + "ties" where words
    are in different columns but should be linked.
    """
    word1_right_edge = word1.hpos + word1.width
    word2_left_edge = word2.hpos
    
    # Check if word1 is at a right edge
    is_word1_at_right_edge = False
    word1_column_idx = None
    for i, right_edge in enumerate(column_boundaries['right_edges']):
        if abs(word1_right_edge - right_edge) < 100:  # Within 100 pixels
            is_word1_at_right_edge = True
            word1_column_idx = i
            break
    # Also check typical right edge
    if not is_word1_at_right_edge:
        if abs(word1_right_edge - column_boundaries['typical_right']) < 150:
            is_word1_at_right_edge = True
            # Find which column this is (approximate - use last column index)
            word1_column_idx = len(column_boundaries['right_edges']) - 1 if column_boundaries['right_edges'] else 0
    
    # Check if word2 is at a left edge
    is_word2_at_left_edge = False
    word2_column_idx = None
    for i, left_edge in enumerate(column_boundaries['left_edges']):
        if abs(word2_left_edge - left_edge) < 100:  # Within 100 pixels
            is_word2_at_left_edge = True
            word2_column_idx = i
            break
    # Also check typical left edge
    if not is_word2_at_left_edge:
        if abs(word2_left_edge - column_boundaries['typical_left']) < 150:
            is_word2_at_left_edge = True
            word2_column_idx = 0
    
    # If both are at edges, check if they're in adjacent columns
    if is_word1_at_right_edge and is_word2_at_left_edge:
        # If column indices are available, check adjacency
        if word1_column_idx is not None and word2_column_idx is not None:
            # Adjacent if word2 is in the next column (word2_column_idx == word1_column_idx + 1)
            if word2_column_idx == word1_column_idx + 1:
                return True
        
        # Also check if word2 is to the left of word1 (wrapped to next column)
        # This handles cases where word1 is at right edge and word2 is at left edge
        # even if exact column indices cannot be determined
        if word2.hpos < word1.hpos:
            return True
    
    return False


def calculate_column_aware_threshold(page, column_boundaries: Dict[str, List[int]]) -> float:
    """
    Calculate a column-aware distance threshold for reading order matching.
    
    Uses column boundaries to determine a reasonable maximum distance,
    rather than an arbitrary pixel value.
    
    Returns a threshold that allows up to approximately 2 column heights
    of vertical distance in reading order.
    """
    if page is None:
        return 2000.0  # Fallback threshold
    
    # Estimate number of columns from detected column boundaries
    num_columns = max(len(column_boundaries['left_edges']), 1)
    
    # Estimate typical column height
    # For multi-column layouts, column height is roughly page height
    # For single column, use page height
    estimated_column_height = page.height if num_columns == 1 else page.height
    
    # Allow up to 2x column height in reading order distance
    # This accounts for cases where words might be separated by a column break
    # but are still within reasonable reading order distance
    threshold = estimated_column_height * 2.0
    
    return threshold


def calculate_reading_order_distance(word1, word2, page=None, column_boundaries: Optional[Dict[str, List[int]]] = None) -> float:
    """
    Calculate reading order distance between two words, accounting for:
    - Line wrapping (word at end of line, next word at start of next line)
    - Column wrapping (word at right edge, next word at left edge of next column)
    - Bottom-right to top-left wrapping (word at bottom right, next word at top left)
    
    Returns a distance score where lower is better (closer in reading order).
    """
    hpos1, vpos1 = word1.hpos, word1.vpos
    hpos2, vpos2 = word2.hpos, word2.vpos
    width1, height1 = word1.width, word1.height
    width2, height2 = word2.width, word2.height
    
    # Calculate basic differences
    hpos_diff = abs(hpos1 - hpos2)
    vpos_diff = abs(vpos1 - vpos2)
    
    # Check if word1 is at the end of a line (right edge)
    word1_right_edge = hpos1 + width1
    word2_left_edge = hpos2
    
    # Get column boundaries (detect if not provided)
    if column_boundaries is None:
        column_boundaries = detect_column_boundaries(page)
    
    # Check if word2 is at the start of a line (left edge)
    # Check if it's close to any detected left edge position
    is_word2_at_left_edge = False
    for left_edge in column_boundaries['left_edges']:
        if abs(word2_left_edge - left_edge) < 100:  # Within 100 pixels of a left edge
            is_word2_at_left_edge = True
            break
    # Also check if it's close to the typical left edge
    if not is_word2_at_left_edge:
        is_word2_at_left_edge = abs(word2_left_edge - column_boundaries['typical_left']) < 150
    
    # Check if word1 is at right edge
    # Method 1: Words ending with hyphens are almost always at the end of a line
    decoded_content1 = getattr(word1, 'content', '')
    is_hyphen_ending = decoded_content1.rstrip().endswith(("-", "-", "—", "--"))
    
    # Method 2: Check if after_word exists and is on a different line (line wrap)
    # This handles cases like "dams" + "aged" = "damaged" where there's no literal hyphen
    is_at_line_end_by_after_word = False
    if hasattr(word1, 'after_word') and word1.after_word is not None:
        after_vpos = word1.after_word.vpos
        after_hpos = word1.after_word.hpos
        # If after_word is on a different line (different vpos) and starts at left edge
        vpos_diff_with_after = abs(vpos1 - after_vpos)
        if vpos_diff_with_after > 20:  # Different line
            # Check if after_word is at a detected left edge
            for left_edge in column_boundaries['left_edges']:
                if abs(after_hpos - left_edge) < 100:
                    is_at_line_end_by_after_word = True
                    break
            if not is_at_line_end_by_after_word:
                # Check if close to typical left edge
                is_at_line_end_by_after_word = abs(after_hpos - column_boundaries['typical_left']) < 150
    
    is_word1_at_right_edge = False
    if is_hyphen_ending or is_at_line_end_by_after_word:
        # Words ending with hyphens OR words whose after_word is on next line at left edge
        is_word1_at_right_edge = True
    else:
        # Check if word1 is close to any detected right edge position
        for right_edge in column_boundaries['right_edges']:
            if abs(word1_right_edge - right_edge) < 100:  # Within 100 pixels of a right edge
                is_word1_at_right_edge = True
                break
        # Also check if close to typical right edge
        if not is_word1_at_right_edge:
            is_word1_at_right_edge = abs(word1_right_edge - column_boundaries['typical_right']) < 150
        # Fallback: check if near page edge
        if not is_word1_at_right_edge and page:
            page_width = page.width
            is_word1_at_right_edge = word1_right_edge > (page_width * 0.7)  # Within 30% of right edge
    
    # Case 1: Same line (small vpos difference, typically < 50 pixels)
    if vpos_diff < 50:
        # On same line, use horizontal distance
        return hpos_diff
    
    # Case 2: Line wrap in same column
    # Word1 at right edge, word2 at left edge of next line, similar hpos range
    if (is_word1_at_right_edge and is_word2_at_left_edge and 
        vpos_diff < 100 and  # Close vertically (next line)
        hpos_diff < 1000):  # Not too far horizontally
        # This is a line wrap - very close in reading order
        return vpos_diff * 0.1  # Small penalty for line wrap
    
    # Case 3: Column wrap
    # Word1 at right edge of one column, word2 at left edge of next column
    # Large hpos difference but word2 has lower hpos (wrapped to next column)
    if (is_word1_at_right_edge and is_word2_at_left_edge and
        hpos2 < hpos1 and  # word2 is to the left (wrapped)
        vpos_diff < 200):  # Reasonably close vertically
        # Column wrap - moderate distance
        return (vpos_diff * 10) + (hpos_diff * 0.1)
    
    # Case 4: Bottom-right to top-left (next column, different area)
    # Word1 at bottom right, word2 at top left of next column
    if (is_word1_at_right_edge and is_word2_at_left_edge and
        vpos2 < vpos1 and  # word2 is above (wrapped to next column)
        hpos2 < hpos1):  # word2 is to the left
        # Bottom-right to top-left wrap
        return (abs(vpos1 - vpos2) * 10) + (hpos_diff * 0.1)
    
    # Default: Use weighted combination (vpos weighted more heavily)
    return (vpos_diff * 1000) + hpos_diff


def calculate_proximity_score(
    hypothesis,
    candidate_llm_token,
    llm_elements,
    hypothesis_list
) -> float:
    """
    Calculate a proximity score for a candidate LLM token based on:
    1. Sequence consistency with already-matched neighbors
    2. Geometric position relative to neighbors
    
    Returns a score from 0.0 to 100.0, where higher is better.
    """
    if not llm_elements:
        return 0.0
    
    # Get LLM token index in the sequence
    try:
        llm_token_index = llm_elements.index(candidate_llm_token)
    except ValueError:
        return 0.0
    
    score = 0.0
    factors = []
    
    # Factor 1: Sequence consistency with left neighbor
    if hypothesis.anchor.before_word is not None:
        # Find the hypothesis for the before word
        before_hyp = None
        for hyp in hypothesis_list:
            if hyp.anchor == hypothesis.anchor.before_word:
                before_hyp = hyp
                break
        
        if before_hyp and before_hyp.chosen_LLM_token:
            # Check if the sequence is consistent
            try:
                before_llm_index = llm_elements.index(before_hyp.chosen_LLM_token)
                expected_index = before_llm_index + 1
                if llm_token_index == expected_index:
                    # Perfect sequence match
                    factors.append(("left_sequence", 100.0))
                else:
                    # Penalize based on distance from expected position
                    distance = abs(llm_token_index - expected_index)
                    # Score decreases with distance, but not too harshly
                    sequence_score = max(0.0, 100.0 - (distance * 10.0))
                    factors.append(("left_sequence", sequence_score))
            except ValueError:
                pass
    
    # Factor 2: Sequence consistency with right neighbor
    if hypothesis.anchor.after_word is not None:
        # Find the hypothesis for the after word
        after_hyp = None
        for hyp in hypothesis_list:
            if hyp.anchor == hypothesis.anchor.after_word:
                after_hyp = hyp
                break
        
        if after_hyp and after_hyp.chosen_LLM_token:
            # Check if the sequence is consistent
            try:
                after_llm_index = llm_elements.index(after_hyp.chosen_LLM_token)
                expected_index = after_llm_index - 1
                if llm_token_index == expected_index:
                    # Perfect sequence match
                    factors.append(("right_sequence", 100.0))
                else:
                    # Penalize based on distance from expected position
                    distance = abs(llm_token_index - expected_index)
                    sequence_score = max(0.0, 100.0 - (distance * 10.0))
                    factors.append(("right_sequence", sequence_score))
            except ValueError:
                pass
    
    # Factor 3: Geometric proximity (if position info from neighbors is available)
    # Calculate expected position based on neighbors' positions
    if hypothesis.anchor.before_word is not None and hypothesis.anchor.after_word is not None:
        before_hyp = None
        after_hyp = None
        for hyp in hypothesis_list:
            if hyp.anchor == hypothesis.anchor.before_word:
                before_hyp = hyp
            if hyp.anchor == hypothesis.anchor.after_word:
                after_hyp = hyp
        
        if before_hyp and after_hyp and before_hyp.chosen_LLM_token and after_hyp.chosen_LLM_token:
            try:
                before_llm_index = llm_elements.index(before_hyp.chosen_LLM_token)
                after_llm_index = llm_elements.index(after_hyp.chosen_LLM_token)
                
                # Calculate expected hpos based on interpolation
                before_hpos = before_hyp.anchor.hpos
                after_hpos = after_hyp.anchor.hpos
                expected_hpos = (before_hpos + after_hpos) / 2.0
                
                # Calculate distance from expected position
                actual_hpos = hypothesis.anchor.hpos
                hpos_distance = abs(actual_hpos - expected_hpos)
                
                # Normalize distance (assuming average word width ~100-200 pixels)
                # Score decreases with distance
                if hpos_distance < 100:
                    geometric_score = 100.0
                elif hpos_distance < 500:
                    geometric_score = max(0.0, 100.0 - ((hpos_distance - 100) / 4.0))
                else:
                    geometric_score = 0.0
                
                factors.append(("geometric", geometric_score))
            except (ValueError, ZeroDivisionError):
                pass
    
    # Combine factors (weighted average)
    if factors:
        # Weight sequence factors more heavily than geometric
        total_weight = 0.0
        weighted_sum = 0.0
        for factor_name, factor_score in factors:
            if "sequence" in factor_name:
                weight = 2.0  # Sequence is more important
            else:
                weight = 1.0
            weighted_sum += factor_score * weight
            total_weight += weight
        
        if total_weight > 0:
            score = weighted_sum / total_weight
    
    return score


def assess_proximity_for_multiple_matches(
    hypothesis,
    llm_elements,
    hypothesis_list
):
    """
    When a hypothesis has multiple perfect context matches, use proximity assessment
    to select the best one.
    
    Returns the best LLM token based on proximity, or None if no good match found.
    """
    if not hypothesis.best_candidates_by_context or len(hypothesis.best_candidates_by_context) <= 1:
        return None
    
    # Calculate proximity scores for each perfect match
    scored_candidates = []
    for candidate, llm_token, before_score, after_score in hypothesis.best_candidates_by_context:
        proximity = calculate_proximity_score(hypothesis, llm_token, llm_elements, hypothesis_list)
        # Combine context score (already 100/100) with proximity
        # For now, use proximity as tie-breaker
        total_score = (before_score + after_score) / 2.0 + (proximity * 0.1)  # Small weight for proximity
        scored_candidates.append((candidate, llm_token, total_score, proximity))
    
    # Sort by total score (descending)
    scored_candidates.sort(key=lambda x: x[2], reverse=True)
    
    # Return the best one
    if scored_candidates:
        return scored_candidates[0][1]  # Return the LLM token
    
    return None

