"""
Proximity scoring functions for text boundary mapping.

This module handles proximity-based selection when multiple perfect context matches exist.
It uses sequence consistency and geometric position to determine the best match.

Generated by Cursor Agent with detailed instructions about the purpose of the module, cases needing to be handled, and context for the logic.
"""

from typing import List, Optional, Dict, Tuple, TYPE_CHECKING
from collections import defaultdict, Counter

# Import types at runtime - using lazy import to avoid circular dependency
if TYPE_CHECKING:
    from map_up_text import LLMToken, TokenHypotheses
    import xml_obj as XMLOBJ
else:
    # At runtime, we'll import inside functions to avoid circular imports
    LLMToken = None
    TokenHypotheses = None
    XMLOBJ = None

# ============================================================================
# CONFIGURATION CONSTANTS
# ============================================================================

# Column boundary detection
CLUSTER_TOLERANCE_PIXELS = 100  # Positions within this distance are clustered together
TYPICAL_EDGE_TOLERANCE_PIXELS = 150  # Tolerance for matching typical left/right edges
EDGE_MATCH_TOLERANCE_PIXELS = 100  # Tolerance for matching specific edge positions

# Reading order distance calculation
SAME_LINE_VERTICAL_THRESHOLD = 50  # Pixels - words on same line if vpos diff < this
LINE_WRAP_VERTICAL_THRESHOLD = 100  # Pixels - line wrap if vpos diff < this
LINE_WRAP_HORIZONTAL_THRESHOLD = 1000  # Pixels - line wrap if hpos diff < this
COLUMN_WRAP_VERTICAL_THRESHOLD = 200  # Pixels - column wrap if vpos diff < this
PAGE_EDGE_THRESHOLD_RATIO = 0.7  # Word is at right edge if > 70% of page width
DIFFERENT_LINE_VPOS_THRESHOLD = 20  # Pixels - different line if vpos diff > this

# Reading order distance weights
LINE_WRAP_DISTANCE_MULTIPLIER = 0.1  # Small penalty for line wrap
COLUMN_WRAP_VPOS_MULTIPLIER = 10  # Vertical distance multiplier for column wrap
COLUMN_WRAP_HPOS_MULTIPLIER = 0.1  # Horizontal distance multiplier for column wrap
DEFAULT_VPOS_MULTIPLIER = 1000  # Default vertical position weight
COLUMN_HEIGHT_MULTIPLIER = 2.0  # Allow up to 2x column height in reading order

# Proximity scoring
SEQUENCE_PENALTY_PER_POSITION = 10.0  # Score penalty per position away from expected
PERFECT_SEQUENCE_SCORE = 100.0  # Score for perfect sequence match
GEOMETRIC_CLOSE_THRESHOLD = 100  # Pixels - perfect geometric score if within this
GEOMETRIC_FAR_THRESHOLD = 500  # Pixels - zero geometric score if beyond this
GEOMETRIC_SCORE_DECAY_RATE = 4.0  # Rate at which geometric score decays
SEQUENCE_FACTOR_WEIGHT = 2.0  # Weight for sequence factors in proximity scoring
GEOMETRIC_FACTOR_WEIGHT = 1.0  # Weight for geometric factors in proximity scoring
PROXIMITY_TIEBREAKER_WEIGHT = 0.1  # Weight for proximity score as tiebreaker

# Fallback values (when page is None)
FALLBACK_LEFT_EDGES = [0, 600]
FALLBACK_RIGHT_EDGES = [2000, 4000]
FALLBACK_TYPICAL_LEFT = 500
FALLBACK_TYPICAL_RIGHT = 2000
FALLBACK_DISTANCE_THRESHOLD = 2000.0

# Hyphen characters that indicate line end
HYPHEN_CHARACTERS = ("-", "-", "—", "--")


# ============================================================================
# COLUMN BOUNDARY DETECTION HELPERS
# ============================================================================

def _collect_page_positions(page) -> Tuple[List[int], List[int]]:
    """
    Collect all left and right positions from page elements.
    
    Returns:
        Tuple of (left_positions, right_positions) lists
    """
    left_positions = []
    right_positions = []
    
    for block in page.content_elements:
        # TextBlock boundaries
        left_positions.append(block.hpos)
        right_positions.append(block.hpos + block.width)
        
        for line in block.content_elements:
            # TextLine boundaries
            left_positions.append(line.hpos)
            right_positions.append(line.hpos + line.width)
            
            # Also check first and last words in each line
            if line.content_elements:
                first_word = line.content_elements[0]
                last_word = line.content_elements[-1]
                left_positions.append(first_word.hpos)
                right_positions.append(last_word.hpos + last_word.width)
    
    return left_positions, right_positions


def _cluster_positions(positions: List[int], tolerance: int = CLUSTER_TOLERANCE_PIXELS) -> List[List[int]]:
    """
    Cluster positions that are within tolerance of each other.
    
    Args:
        positions: Sorted list of positions
        tolerance: Maximum distance for positions to be in same cluster
        
    Returns:
        List of clusters, where each cluster is a list of positions
    """
    if not positions:
        return []
    
    sorted_positions = sorted(positions)
    clusters = []
    current_cluster = [sorted_positions[0]]
    
    for pos in sorted_positions[1:]:
        if pos - current_cluster[-1] < tolerance:
            current_cluster.append(pos)
        else:
            clusters.append(current_cluster)
            current_cluster = [pos]
    clusters.append(current_cluster)
    
    return clusters


def _get_representative_edges(clusters: List[List[int]]) -> List[int]:
    """
    Get representative edge positions from clusters (median of each cluster).
    
    Args:
        clusters: List of position clusters
        
    Returns:
        List of representative edge positions
    """
    edges = []
    for cluster in clusters:
        if len(cluster) > 0:
            sorted_cluster = sorted(cluster)
            median_idx = len(sorted_cluster) // 2
            edges.append(sorted_cluster[median_idx])
    return edges


def _find_typical_position(positions: List[int], fallback: int) -> int:
    """
    Find the most common position in a list.
    
    Args:
        positions: List of positions
        fallback: Value to return if positions list is empty
        
    Returns:
        Most common position, or fallback if no positions
    """
    if not positions:
        return fallback
    counter = Counter(positions)
    return counter.most_common(1)[0][0] if counter else fallback


def detect_column_boundaries(page) -> Dict[str, List[int]]:
    """
    Analyze the page structure to detect column boundaries dynamically.
    
    Returns a dict with:
    - 'left_edges': List of common left edge positions (column starts)
    - 'right_edges': List of common right edge positions (column ends)
    - 'typical_left': Typical left edge position (most common)
    - 'typical_right': Typical right edge position (most common)
    """
    if page is None:
        return {
            'left_edges': FALLBACK_LEFT_EDGES,
            'right_edges': FALLBACK_RIGHT_EDGES,
            'typical_left': FALLBACK_TYPICAL_LEFT,
            'typical_right': FALLBACK_TYPICAL_RIGHT
        }
    
    # Collect all TextBlock and TextLine left/right positions
    left_positions, right_positions = _collect_page_positions(page)
    
    if not left_positions or not right_positions:
        # Fallback to page-based estimates
        return {
            'left_edges': [0, page.width // 2] if page else FALLBACK_LEFT_EDGES,
            'right_edges': [page.width // 2, page.width] if page else FALLBACK_RIGHT_EDGES,
            'typical_left': FALLBACK_TYPICAL_LEFT,
            'typical_right': page.width - 500 if page else FALLBACK_TYPICAL_RIGHT
        }
    
    # Cluster and find representative edges
    left_clusters = _cluster_positions(left_positions)
    right_clusters = _cluster_positions(right_positions)
    
    left_edges = _get_representative_edges(left_clusters)
    right_edges = _get_representative_edges(right_clusters)
    
    # Find most common (typical) positions
    typical_left = _find_typical_position(left_positions, FALLBACK_TYPICAL_LEFT)
    typical_right = _find_typical_position(right_positions, 
                                          page.width - 500 if page else FALLBACK_TYPICAL_RIGHT)
    
    return {
        'left_edges': sorted(set(left_edges)),
        'right_edges': sorted(set(right_edges)),
        'typical_left': typical_left,
        'typical_right': typical_right
    }


# ============================================================================
# EDGE DETECTION HELPERS
# ============================================================================

def _is_position_at_edge(position: int, edge_positions: List[int], 
                         typical_edge: int, 
                         specific_tolerance: int = EDGE_MATCH_TOLERANCE_PIXELS,
                         typical_tolerance: int = TYPICAL_EDGE_TOLERANCE_PIXELS) -> Tuple[bool, Optional[int]]:
    """
    Check if a position is at an edge, and return which edge index if found.
    
    Args:
        position: Position to check
        edge_positions: List of specific edge positions
        typical_edge: Typical edge position
        specific_tolerance: Tolerance for matching specific edges
        typical_tolerance: Tolerance for matching typical edge
        
    Returns:
        Tuple of (is_at_edge, edge_index or None)
    """
    # Check specific edge positions
    for i, edge_pos in enumerate(edge_positions):
        if abs(position - edge_pos) < specific_tolerance:
            return True, i
    
    # Check typical edge
    if abs(position - typical_edge) < typical_tolerance:
        # For typical edge, return approximate index
        edge_idx = len(edge_positions) - 1 if edge_positions else 0
        return True, edge_idx
    
    return False, None


def _is_word_at_left_edge(word, column_boundaries: Dict[str, List[int]]) -> Tuple[bool, Optional[int]]:
    """
    Check if a word is at a left edge.
    
    Returns:
        Tuple of (is_at_left_edge, column_index or None)
    """
    word_left_edge = word.hpos
    return _is_position_at_edge(
        word_left_edge,
        column_boundaries['left_edges'],
        column_boundaries['typical_left']
    )


def _is_word_at_right_edge(word, column_boundaries: Dict[str, List[int]], 
                           page=None) -> Tuple[bool, Optional[int]]:
    """
    Check if a word is at a right edge.
    
    Returns:
        Tuple of (is_at_right_edge, column_index or None)
    """
    word_right_edge = word.hpos + word.width
    
    # First check detected edges
    is_at_edge, edge_idx = _is_position_at_edge(
        word_right_edge,
        column_boundaries['right_edges'],
        column_boundaries['typical_right']
    )
    
    if is_at_edge:
        return True, edge_idx
    
    # Fallback: check if near page edge
    if page and word_right_edge > (page.width * PAGE_EDGE_THRESHOLD_RATIO):
        return True, None
    
    return False, None


def _is_word_at_line_end_by_hyphen(word) -> bool:
    """
    Check if word ends with a hyphen character (indicating line end).
    """
    decoded_content = getattr(word, 'content', '')
    return decoded_content.rstrip().endswith(HYPHEN_CHARACTERS)


def _is_word_at_line_end_by_after_word(word, column_boundaries: Dict[str, List[int]]) -> bool:
    """
    Check if word is at line end by examining its after_word position.
    
    This handles cases like "dams" + "aged" = "damaged" where there's no literal hyphen.
    """
    if not (hasattr(word, 'after_word') and word.after_word is not None):
        return False
    
    after_vpos = word.after_word.vpos
    after_hpos = word.after_word.hpos
    word_vpos = word.vpos
    
    # Check if after_word is on a different line
    vpos_diff = abs(word_vpos - after_vpos)
    if vpos_diff <= DIFFERENT_LINE_VPOS_THRESHOLD:
        return False
    
    # Check if after_word is at a detected left edge
    is_at_left, _ = _is_word_at_left_edge(word.after_word, column_boundaries)
    return is_at_left


def is_word_at_right_edge(word, column_boundaries: Dict[str, List[int]], 
                          page=None) -> bool:
    """
    Check if a word is at the right edge of a line/column.
    
    Uses multiple heuristics:
    1. Word ends with hyphen
    2. Word's after_word is on next line at left edge
    3. Word is close to detected right edge positions
    4. Word is near page edge
    
    Returns:
        True if word is at right edge
    """
    # Method 1: Words ending with hyphens
    if _is_word_at_line_end_by_hyphen(word):
        return True
    
    # Method 2: Check if after_word is on next line at left edge
    if _is_word_at_line_end_by_after_word(word, column_boundaries):
        return True
    
    # Method 3: Check detected edges
    is_at_edge, _ = _is_word_at_right_edge(word, column_boundaries, page)
    return is_at_edge


def are_words_in_adjacent_columns(word1, word2, column_boundaries: Dict[str, List[int]]) -> bool:
    """
    Check if two words are in adjacent columns.
    
    Returns True if:
    - word1 is at the right edge of one column AND
    - word2 is at the left edge of the next column
    
    This handles cross-column hyphenation like "sor-" + "ties" where words
    are in different columns but should be linked.
    """
    # Check if word1 is at a right edge
    is_word1_at_right, word1_column_idx = _is_word_at_right_edge(word1, column_boundaries)
    
    # Check if word2 is at a left edge
    is_word2_at_left, word2_column_idx = _is_word_at_left_edge(word2, column_boundaries)
    
    # If both are at edges, check if they're in adjacent columns
    if is_word1_at_right and is_word2_at_left:
        # If column indices are available, check adjacency
        if word1_column_idx is not None and word2_column_idx is not None:
            # Adjacent if word2 is in the next column
            if word2_column_idx == word1_column_idx + 1:
                return True
        
        # Also check if word2 is to the left of word1 (wrapped to next column)
        # This handles cases where exact column indices cannot be determined
        if word2.hpos < word1.hpos:
            return True
    
    return False


# ============================================================================
# READING ORDER DISTANCE CALCULATION HELPERS
# ============================================================================

def _calculate_same_line_distance(hpos1: int, hpos2: int) -> float:
    """
    Calculate distance for words on the same line.
    
    Args:
        hpos1: Horizontal position of first word
        hpos2: Horizontal position of second word
        
    Returns:
        Horizontal distance
    """
    return abs(hpos1 - hpos2)


def _calculate_line_wrap_distance(vpos1: int, vpos2: int) -> float:
    """
    Calculate distance for line wrap (word at end of line, next at start of next line).
    
    Args:
        vpos1: Vertical position of first word
        vpos2: Vertical position of second word
        
    Returns:
        Small penalty for line wrap
    """
    vpos_diff = abs(vpos1 - vpos2)
    return vpos_diff * LINE_WRAP_DISTANCE_MULTIPLIER


def _calculate_column_wrap_distance(hpos1: int, hpos2: int, vpos1: int, vpos2: int) -> float:
    """
    Calculate distance for column wrap (word at right edge, next at left edge of next column).
    
    Args:
        hpos1: Horizontal position of first word
        hpos2: Horizontal position of second word
        vpos1: Vertical position of first word
        vpos2: Vertical position of second word
        
    Returns:
        Moderate distance for column wrap
    """
    vpos_diff = abs(vpos1 - vpos2)
    hpos_diff = abs(hpos1 - hpos2)
    return (vpos_diff * COLUMN_WRAP_VPOS_MULTIPLIER) + (hpos_diff * COLUMN_WRAP_HPOS_MULTIPLIER)


def _calculate_bottom_right_to_top_left_distance(hpos1: int, hpos2: int, vpos1: int, vpos2: int) -> float:
    """
    Calculate distance for bottom-right to top-left wrap (next column, different area).
    
    Args:
        hpos1: Horizontal position of first word
        hpos2: Horizontal position of second word
        vpos1: Vertical position of first word
        vpos2: Vertical position of second word
        
    Returns:
        Distance for bottom-right to top-left wrap
    """
    vpos_diff = abs(vpos1 - vpos2)
    hpos_diff = abs(hpos1 - hpos2)
    return (vpos_diff * COLUMN_WRAP_VPOS_MULTIPLIER) + (hpos_diff * COLUMN_WRAP_HPOS_MULTIPLIER)


def _calculate_default_distance(hpos1: int, hpos2: int, vpos1: int, vpos2: int) -> float:
    """
    Calculate default distance using weighted combination.
    
    Args:
        hpos1: Horizontal position of first word
        hpos2: Horizontal position of second word
        vpos1: Vertical position of first word
        vpos2: Vertical position of second word
        
    Returns:
        Weighted distance (vpos weighted more heavily)
    """
    vpos_diff = abs(vpos1 - vpos2)
    hpos_diff = abs(hpos1 - hpos2)
    return (vpos_diff * DEFAULT_VPOS_MULTIPLIER) + hpos_diff


def calculate_column_aware_threshold(page, column_boundaries: Dict[str, List[int]]) -> float:
    """
    Calculate a column-aware distance threshold for reading order matching.
    
    Uses column boundaries to determine a reasonable maximum distance,
    rather than an arbitrary pixel value.
    
    Returns a threshold that allows up to approximately 2 column heights
    of vertical distance in reading order.
    """
    if page is None:
        return FALLBACK_DISTANCE_THRESHOLD
    
    # Estimate number of columns from detected column boundaries
    num_columns = max(len(column_boundaries['left_edges']), 1)
    
    # Estimate typical column height
    # For multi-column layouts, column height is roughly page height
    # For single column, use page height
    estimated_column_height = page.height
    
    # Allow up to 2x column height in reading order distance
    # This accounts for cases where words might be separated by a column break
    # but are still within reasonable reading order distance
    threshold = estimated_column_height * COLUMN_HEIGHT_MULTIPLIER
    
    return threshold


def calculate_reading_order_distance(word1, word2, page=None, column_boundaries: Optional[Dict[str, List[int]]] = None) -> float:
    """
    Calculate reading order distance between two words, accounting for:
    - Line wrapping (word at end of line, next word at start of next line)
    - Column wrapping (word at right edge, next word at left edge of next column)
    - Bottom-right to top-left wrapping (word at bottom right, next word at top left)
    
    Returns a distance score where lower is better (closer in reading order).
    """
    hpos1, vpos1 = word1.hpos, word1.vpos
    hpos2, vpos2 = word2.hpos, word2.vpos
    
    # Calculate basic differences
    hpos_diff = abs(hpos1 - hpos2)
    vpos_diff = abs(vpos1 - vpos2)
    
    # Get column boundaries (detect if not provided)
    if column_boundaries is None:
        column_boundaries = detect_column_boundaries(page)
    
    # Check edge positions
    is_word1_at_right_edge = is_word_at_right_edge(word1, column_boundaries, page)
    is_word2_at_left_edge, _ = _is_word_at_left_edge(word2, column_boundaries)
    
    # Case 1: Same line (small vpos difference)
    if vpos_diff < SAME_LINE_VERTICAL_THRESHOLD:
        return _calculate_same_line_distance(hpos1, hpos2)
    
    # Case 2: Line wrap in same column
    # Word1 at right edge, word2 at left edge of next line, similar hpos range
    if (is_word1_at_right_edge and is_word2_at_left_edge and 
        vpos_diff < LINE_WRAP_VERTICAL_THRESHOLD and
        hpos_diff < LINE_WRAP_HORIZONTAL_THRESHOLD):
        return _calculate_line_wrap_distance(vpos1, vpos2)
    
    # Case 3: Column wrap
    # Word1 at right edge of one column, word2 at left edge of next column
    # Large hpos difference but word2 has lower hpos (wrapped to next column)
    if (is_word1_at_right_edge and is_word2_at_left_edge and
        hpos2 < hpos1 and  # word2 is to the left (wrapped)
        vpos_diff < COLUMN_WRAP_VERTICAL_THRESHOLD):
        return _calculate_column_wrap_distance(hpos1, hpos2, vpos1, vpos2)
    
    # Case 4: Bottom-right to top-left (next column, different area)
    # Word1 at bottom right, word2 at top left of next column
    if (is_word1_at_right_edge and is_word2_at_left_edge and
        vpos2 < vpos1 and  # word2 is above (wrapped to next column)
        hpos2 < hpos1):  # word2 is to the left
        return _calculate_bottom_right_to_top_left_distance(hpos1, hpos2, vpos1, vpos2)
    
    # Default: Use weighted combination (vpos weighted more heavily)
    return _calculate_default_distance(hpos1, hpos2, vpos1, vpos2)


# ============================================================================
# PROXIMITY SCORING HELPERS
# ============================================================================

def _find_hypothesis_for_word(word, hypothesis_list):
    """
    Find the hypothesis object for a given word.
    
    Args:
        word: Word to find hypothesis for
        hypothesis_list: List of all hypotheses
        
    Returns:
        Hypothesis object or None
    """
    for hyp in hypothesis_list:
        if hyp.anchor == word:
            return hyp
    return None


def _calculate_sequence_score(actual_index: int, expected_index: int) -> float:
    """
    Calculate sequence consistency score.
    
    Args:
        actual_index: Actual LLM token index
        expected_index: Expected LLM token index
        
    Returns:
        Score from 0.0 to 100.0
    """
    if actual_index == expected_index:
        return PERFECT_SEQUENCE_SCORE
    
    # Penalize based on distance from expected position
    distance = abs(actual_index - expected_index)
    return max(0.0, PERFECT_SEQUENCE_SCORE - (distance * SEQUENCE_PENALTY_PER_POSITION))


def _calculate_left_sequence_factor(hypothesis, llm_token_index: int, 
                                     llm_elements: List, hypothesis_list: List) -> Optional[float]:
    """
    Calculate sequence consistency score with left neighbor.
    
    Returns:
        Score from 0.0 to 100.0, or None if not applicable
    """
    if hypothesis.anchor.before_word is None:
        return None
    
    before_hyp = _find_hypothesis_for_word(hypothesis.anchor.before_word, hypothesis_list)
    if not (before_hyp and before_hyp.chosen_LLM_token):
        return None
    
    try:
        before_llm_index = llm_elements.index(before_hyp.chosen_LLM_token)
        expected_index = before_llm_index + 1
        return _calculate_sequence_score(llm_token_index, expected_index)
    except ValueError:
        return None


def _calculate_right_sequence_factor(hypothesis, llm_token_index: int,
                                      llm_elements: List, hypothesis_list: List) -> Optional[float]:
    """
    Calculate sequence consistency score with right neighbor.
    
    Returns:
        Score from 0.0 to 100.0, or None if not applicable
    """
    if hypothesis.anchor.after_word is None:
        return None
    
    after_hyp = _find_hypothesis_for_word(hypothesis.anchor.after_word, hypothesis_list)
    if not (after_hyp and after_hyp.chosen_LLM_token):
        return None
    
    try:
        after_llm_index = llm_elements.index(after_hyp.chosen_LLM_token)
        expected_index = after_llm_index - 1
        return _calculate_sequence_score(llm_token_index, expected_index)
    except ValueError:
        return None


def _calculate_geometric_factor(hypothesis, llm_elements: List, 
                                 hypothesis_list: List) -> Optional[float]:
    """
    Calculate geometric proximity score based on neighbors' positions.
    
    Returns:
        Score from 0.0 to 100.0, or None if not applicable
    """
    if (hypothesis.anchor.before_word is None or 
        hypothesis.anchor.after_word is None):
        return None
    
    before_hyp = _find_hypothesis_for_word(hypothesis.anchor.before_word, hypothesis_list)
    after_hyp = _find_hypothesis_for_word(hypothesis.anchor.after_word, hypothesis_list)
    
    if not (before_hyp and after_hyp and 
            before_hyp.chosen_LLM_token and after_hyp.chosen_LLM_token):
        return None
    
    try:
        # Verify both neighbors have valid LLM tokens in the sequence
        before_llm_index = llm_elements.index(before_hyp.chosen_LLM_token)
        after_llm_index = llm_elements.index(after_hyp.chosen_LLM_token)
        
        # Calculate expected hpos based on interpolation
        before_hpos = before_hyp.anchor.hpos
        after_hpos = after_hyp.anchor.hpos
        expected_hpos = (before_hpos + after_hpos) / 2.0
        
        # Calculate distance from expected position
        actual_hpos = hypothesis.anchor.hpos
        hpos_distance = abs(actual_hpos - expected_hpos)
        
        # Normalize distance
        if hpos_distance < GEOMETRIC_CLOSE_THRESHOLD:
            return PERFECT_SEQUENCE_SCORE
        elif hpos_distance < GEOMETRIC_FAR_THRESHOLD:
            return max(0.0, PERFECT_SEQUENCE_SCORE - 
                      ((hpos_distance - GEOMETRIC_CLOSE_THRESHOLD) / GEOMETRIC_SCORE_DECAY_RATE))
        else:
            return 0.0
    except (ValueError, ZeroDivisionError):
        return None


def _combine_proximity_factors(factors: List[Tuple[str, float]]) -> float:
    """
    Combine proximity scoring factors using weighted average.
    
    Args:
        factors: List of (factor_name, factor_score) tuples
        
    Returns:
        Combined score from 0.0 to 100.0
    """
    if not factors:
        return 0.0
    
    total_weight = 0.0
    weighted_sum = 0.0
    
    for factor_name, factor_score in factors:
        if "sequence" in factor_name:
            weight = SEQUENCE_FACTOR_WEIGHT
        else:
            weight = GEOMETRIC_FACTOR_WEIGHT
        
        weighted_sum += factor_score * weight
        total_weight += weight
    
    if total_weight > 0:
        return weighted_sum / total_weight
    
    return 0.0


def calculate_proximity_score(
    hypothesis,
    candidate_llm_token,
    llm_elements,
    hypothesis_list
) -> float:
    """
    Calculate a proximity score for a candidate LLM token based on:
    1. Sequence consistency with already-matched neighbors
    2. Geometric position relative to neighbors
    
    Returns a score from 0.0 to 100.0, where higher is better.
    """
    if not llm_elements:
        return 0.0
    
    # Get LLM token index in the sequence
    try:
        llm_token_index = llm_elements.index(candidate_llm_token)
    except ValueError:
        return 0.0
    
    factors = []
    
    # Factor 1: Sequence consistency with left neighbor
    left_sequence_score = _calculate_left_sequence_factor(
        hypothesis, llm_token_index, llm_elements, hypothesis_list
    )
    if left_sequence_score is not None:
        factors.append(("left_sequence", left_sequence_score))
    
    # Factor 2: Sequence consistency with right neighbor
    right_sequence_score = _calculate_right_sequence_factor(
        hypothesis, llm_token_index, llm_elements, hypothesis_list
    )
    if right_sequence_score is not None:
        factors.append(("right_sequence", right_sequence_score))
    
    # Factor 3: Geometric proximity
    geometric_score = _calculate_geometric_factor(hypothesis, llm_elements, hypothesis_list)
    if geometric_score is not None:
        factors.append(("geometric", geometric_score))
    
    # Combine factors
    return _combine_proximity_factors(factors)


# ============================================================================
# MULTIPLE MATCHES ASSESSMENT
# ============================================================================

def assess_proximity_for_multiple_matches(
    hypothesis,
    llm_elements,
    hypothesis_list
):
    """
    When a hypothesis has multiple perfect context matches, use proximity assessment
    to select the best one.
    
    Returns the best LLM token based on proximity, or None if no good match found.
    """
    if not hypothesis.best_candidates_by_context or len(hypothesis.best_candidates_by_context) <= 1:
        return None
    
    # Calculate proximity scores for each perfect match
    scored_candidates = []
    for candidate, llm_token, before_score, after_score in hypothesis.best_candidates_by_context:
        proximity = calculate_proximity_score(hypothesis, llm_token, llm_elements, hypothesis_list)
        # Combine context score (already 100/100) with proximity as tie-breaker
        context_score = (before_score + after_score) / 2.0
        total_score = context_score + (proximity * PROXIMITY_TIEBREAKER_WEIGHT)
        scored_candidates.append((candidate, llm_token, total_score, proximity))
    
    # Sort by total score (descending)
    scored_candidates.sort(key=lambda x: x[2], reverse=True)
    
    # Return the best one
    if scored_candidates:
        return scored_candidates[0][1]  # Return the LLM token
    
    return None

